# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: default_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='default_settings.proto',
  package='nsjail_programming_server',
  serialized_pb=_b('\n\x16\x64\x65\x66\x61ult_settings.proto\x12\x19nsjail_programming_server\x1a\x0c\x63ommon.proto\"*\n\x13\x43ompilationSettings\x12\x13\n\x0bnsjail_args\x18\x01 \x02(\t\"&\n\x0fRuntimeSettings\x12\x13\n\x0bnsjail_args\x18\x01 \x01(\t\"%\n\x0e\x43ommonSettings\x12\x13\n\x0bnsjail_args\x18\x01 \x01(\t\"\xa8\x02\n\x0fPrivateSettings\x12\x10\n\x08\x62\x61se_dir\x18\x01 \x02(\t\x12\x13\n\x0bnsjail_args\x18\x02 \x02(\t\x12T\n\x1c\x64\x65\x66\x61ult_compilation_settings\x18\x03 \x01(\x0b\x32..nsjail_programming_server.CompilationSettings\x12L\n\x18\x64\x65\x66\x61ult_runtime_settings\x18\x04 \x01(\x0b\x32*.nsjail_programming_server.RuntimeSettings\x12J\n\x17\x64\x65\x66\x61ult_common_settings\x18\x05 \x01(\x0b\x32).nsjail_programming_server.CommonSettings\"\xe6\x02\n\x0ePublicSettings\x12\x13\n\x0bnsjail_path\x18\x01 \x02(\t\x12T\n\x1c\x64\x65\x66\x61ult_compilation_settings\x18\x02 \x01(\x0b\x32..nsjail_programming_server.CompilationSettings\x12L\n\x18\x64\x65\x66\x61ult_runtime_settings\x18\x03 \x01(\x0b\x32*.nsjail_programming_server.RuntimeSettings\x12J\n\x17\x64\x65\x66\x61ult_common_settings\x18\x04 \x01(\x0b\x32).nsjail_programming_server.CommonSettings\x12O\n\x11language_settings\x18\x05 \x03(\x0b\x32\x34.nsjail_programming_server.LanguageDependentSettings\"\x8a\x03\n\x19LanguageDependentSettings\x12\x10\n\x08language\x18\x01 \x02(\t\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\x17\n\x0f\x62inary_filename\x18\x03 \x01(\t\x12`\n\x13\x63ompilation_options\x18\x04 \x01(\x0b\x32\x43.nsjail_programming_server.LanguageDependentSettings.CommandOptions\x12\\\n\x0fruntime_options\x18\x05 \x02(\x0b\x32\x43.nsjail_programming_server.LanguageDependentSettings.CommandOptions\x1ap\n\x0e\x43ommandOptions\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x02(\t\x12\x42\n\x0fresource_limits\x18\x03 \x02(\x0b\x32).nsjail_programming_server.ResourceLimits')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMPILATIONSETTINGS = _descriptor.Descriptor(
  name='CompilationSettings',
  full_name='nsjail_programming_server.CompilationSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nsjail_args', full_name='nsjail_programming_server.CompilationSettings.nsjail_args', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=109,
)


_RUNTIMESETTINGS = _descriptor.Descriptor(
  name='RuntimeSettings',
  full_name='nsjail_programming_server.RuntimeSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nsjail_args', full_name='nsjail_programming_server.RuntimeSettings.nsjail_args', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=149,
)


_COMMONSETTINGS = _descriptor.Descriptor(
  name='CommonSettings',
  full_name='nsjail_programming_server.CommonSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nsjail_args', full_name='nsjail_programming_server.CommonSettings.nsjail_args', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=188,
)


_PRIVATESETTINGS = _descriptor.Descriptor(
  name='PrivateSettings',
  full_name='nsjail_programming_server.PrivateSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_dir', full_name='nsjail_programming_server.PrivateSettings.base_dir', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nsjail_args', full_name='nsjail_programming_server.PrivateSettings.nsjail_args', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_compilation_settings', full_name='nsjail_programming_server.PrivateSettings.default_compilation_settings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_runtime_settings', full_name='nsjail_programming_server.PrivateSettings.default_runtime_settings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_common_settings', full_name='nsjail_programming_server.PrivateSettings.default_common_settings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=487,
)


_PUBLICSETTINGS = _descriptor.Descriptor(
  name='PublicSettings',
  full_name='nsjail_programming_server.PublicSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nsjail_path', full_name='nsjail_programming_server.PublicSettings.nsjail_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_compilation_settings', full_name='nsjail_programming_server.PublicSettings.default_compilation_settings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_runtime_settings', full_name='nsjail_programming_server.PublicSettings.default_runtime_settings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_common_settings', full_name='nsjail_programming_server.PublicSettings.default_common_settings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language_settings', full_name='nsjail_programming_server.PublicSettings.language_settings', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=848,
)


_LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS = _descriptor.Descriptor(
  name='CommandOptions',
  full_name='nsjail_programming_server.LanguageDependentSettings.CommandOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='nsjail_programming_server.LanguageDependentSettings.CommandOptions.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='nsjail_programming_server.LanguageDependentSettings.CommandOptions.args', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource_limits', full_name='nsjail_programming_server.LanguageDependentSettings.CommandOptions.resource_limits', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1133,
  serialized_end=1245,
)

_LANGUAGEDEPENDENTSETTINGS = _descriptor.Descriptor(
  name='LanguageDependentSettings',
  full_name='nsjail_programming_server.LanguageDependentSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='nsjail_programming_server.LanguageDependentSettings.language', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='nsjail_programming_server.LanguageDependentSettings.filename', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary_filename', full_name='nsjail_programming_server.LanguageDependentSettings.binary_filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compilation_options', full_name='nsjail_programming_server.LanguageDependentSettings.compilation_options', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runtime_options', full_name='nsjail_programming_server.LanguageDependentSettings.runtime_options', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=851,
  serialized_end=1245,
)

_PRIVATESETTINGS.fields_by_name['default_compilation_settings'].message_type = _COMPILATIONSETTINGS
_PRIVATESETTINGS.fields_by_name['default_runtime_settings'].message_type = _RUNTIMESETTINGS
_PRIVATESETTINGS.fields_by_name['default_common_settings'].message_type = _COMMONSETTINGS
_PUBLICSETTINGS.fields_by_name['default_compilation_settings'].message_type = _COMPILATIONSETTINGS
_PUBLICSETTINGS.fields_by_name['default_runtime_settings'].message_type = _RUNTIMESETTINGS
_PUBLICSETTINGS.fields_by_name['default_common_settings'].message_type = _COMMONSETTINGS
_PUBLICSETTINGS.fields_by_name['language_settings'].message_type = _LANGUAGEDEPENDENTSETTINGS
_LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS.fields_by_name['resource_limits'].message_type = common_pb2._RESOURCELIMITS
_LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS.containing_type = _LANGUAGEDEPENDENTSETTINGS
_LANGUAGEDEPENDENTSETTINGS.fields_by_name['compilation_options'].message_type = _LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS
_LANGUAGEDEPENDENTSETTINGS.fields_by_name['runtime_options'].message_type = _LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS
DESCRIPTOR.message_types_by_name['CompilationSettings'] = _COMPILATIONSETTINGS
DESCRIPTOR.message_types_by_name['RuntimeSettings'] = _RUNTIMESETTINGS
DESCRIPTOR.message_types_by_name['CommonSettings'] = _COMMONSETTINGS
DESCRIPTOR.message_types_by_name['PrivateSettings'] = _PRIVATESETTINGS
DESCRIPTOR.message_types_by_name['PublicSettings'] = _PUBLICSETTINGS
DESCRIPTOR.message_types_by_name['LanguageDependentSettings'] = _LANGUAGEDEPENDENTSETTINGS

CompilationSettings = _reflection.GeneratedProtocolMessageType('CompilationSettings', (_message.Message,), dict(
  DESCRIPTOR = _COMPILATIONSETTINGS,
  __module__ = 'default_settings_pb2'
  # @@protoc_insertion_point(class_scope:nsjail_programming_server.CompilationSettings)
  ))
_sym_db.RegisterMessage(CompilationSettings)

RuntimeSettings = _reflection.GeneratedProtocolMessageType('RuntimeSettings', (_message.Message,), dict(
  DESCRIPTOR = _RUNTIMESETTINGS,
  __module__ = 'default_settings_pb2'
  # @@protoc_insertion_point(class_scope:nsjail_programming_server.RuntimeSettings)
  ))
_sym_db.RegisterMessage(RuntimeSettings)

CommonSettings = _reflection.GeneratedProtocolMessageType('CommonSettings', (_message.Message,), dict(
  DESCRIPTOR = _COMMONSETTINGS,
  __module__ = 'default_settings_pb2'
  # @@protoc_insertion_point(class_scope:nsjail_programming_server.CommonSettings)
  ))
_sym_db.RegisterMessage(CommonSettings)

PrivateSettings = _reflection.GeneratedProtocolMessageType('PrivateSettings', (_message.Message,), dict(
  DESCRIPTOR = _PRIVATESETTINGS,
  __module__ = 'default_settings_pb2'
  # @@protoc_insertion_point(class_scope:nsjail_programming_server.PrivateSettings)
  ))
_sym_db.RegisterMessage(PrivateSettings)

PublicSettings = _reflection.GeneratedProtocolMessageType('PublicSettings', (_message.Message,), dict(
  DESCRIPTOR = _PUBLICSETTINGS,
  __module__ = 'default_settings_pb2'
  # @@protoc_insertion_point(class_scope:nsjail_programming_server.PublicSettings)
  ))
_sym_db.RegisterMessage(PublicSettings)

LanguageDependentSettings = _reflection.GeneratedProtocolMessageType('LanguageDependentSettings', (_message.Message,), dict(

  CommandOptions = _reflection.GeneratedProtocolMessageType('CommandOptions', (_message.Message,), dict(
    DESCRIPTOR = _LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS,
    __module__ = 'default_settings_pb2'
    # @@protoc_insertion_point(class_scope:nsjail_programming_server.LanguageDependentSettings.CommandOptions)
    ))
  ,
  DESCRIPTOR = _LANGUAGEDEPENDENTSETTINGS,
  __module__ = 'default_settings_pb2'
  # @@protoc_insertion_point(class_scope:nsjail_programming_server.LanguageDependentSettings)
  ))
_sym_db.RegisterMessage(LanguageDependentSettings)
_sym_db.RegisterMessage(LanguageDependentSettings.CommandOptions)


# @@protoc_insertion_point(module_scope)
