# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Scripts and Jobs related to SPoC."""

__author__ = 'Rishav Thakker (rthakker@google.com)'

import csv
import StringIO

from google.appengine.ext import ndb
from models import jobs
from models import roles
from controllers.utils import BaseHandler

from modules.local_chapter import local_chapter_model
from modules.spoc import roles as spoc_roles

RAW_SPOC_DATA = """101,ARUNAI COLLEGE OF ENGINEERING,C A SATHIYA MOORTHY,satya.cas@gmail.com
102,SACRED HEART COLLEGE,MR. R. VEERARAGHAVAN,ragavan.srv@gmail.com
103,KONGUNADU COLLEGE OF ENGINEERING AND TECHNOLOGY,MR M DHARMALINGAM,hodece@kongunadu.ac.in
105,VALLIAMMAI ENGINEERING COLLEGE,DR M ANBUCHEZHIYAN,chezhiyan70@gmail.com
106,SAVEETHA ENGINEERING COLLEGE,DR P VALARMATHIE,valarmathie@saveetha.ac.in
107,KAMARAJ COLLEGE OF ENGINEERING AND TECHNOLOGY,DR  K MUTHULAKSHMI,muthulakshmieee@kamarajengg.edu.in
108,MUTHAYAMMAL ENGINEERING COLLEGE,DR.S.SARAVANAN,saravanan.nivi@gmail.com
110,SSM INSTITUTE OF ENGINEERING AND TECHNOLOGY,MRS S LINGESWARI,lingeswari@gmail.com
111,SRI SIVASUBRAMANIYA NADAR COLLEGE OF ENGINEERING,Dr G SETHURAMAN,sethuramang@ssn.edu.in
112,SASURIE ACADEMY OF ENGINEERING,K.CHENTHIL,saechenthil@gmail.com
113,SVS COLLEGE OF ENGINEERING,M.SIVAKUMAR,siva.recursion@gmail.com
114,SRM UNIVERSITY - RAMAPURAM,MADHAVAN,srmunivrmp.nptel@gmail.com
115,ST.PETERS COLLEGE OF ENGINEERING AND TECHNOLOGY,DR. P. PARTHEEBAN,parthi011@yahoo.co.in
116,GOVERNMENT COLLEGE OF ENGINEERING,DR.I.RAHAMATHULLAH,rahamath.iitm@gmail.com
117,PMC TECH ER.PERUMAL MANIMEKALAI COLLEGE OF ENGINEERING,MR. M. SAHITHULLAH,sahithullahmahaboob@gmail.com
118,AMET UNIVERSITY,DR.V.BALAMURUGAN,ithod@ametuniv.ac.in
119,PRIYADARSHINI ENGINEERING COLLEGE,DR.UMADEVI,uma_san2001@yahoo.co.in
120,THASSIM BEEVI ABDUL KADER COLLEGE FOR WOMEN,J.FATHIMA KALEEMA,tbaknptel@gmail.com
121,NANDHA COLLEGE OF TECHNOLOGY,P.VINOTHKUMAR,vinothkumar.palanisamy@nandhatech.org
122,GNANAMANI COLLEGE OF TECHNOLOGY,DR. P. KUPPUSAMY,nptelgnanamani@gmail.com
123,SNS COLLEGE OF TECHNOLOGY,DR.M.PALANISAMY,librariansnsct@gmail.com
124,K L N COLLEGE OF ENGINEERING,DR.P.GANESH KUMAR,itz.ganeshkumar@gmail.com
125,IDHAYA ENGINEERING COLLEGE FOR WOMEN, CHINNASALEM,T. SUNDARAMURTHY,librarianiec@yahoo.co.in
126,P A C RAMASAMY RAJA POLYTECHINC COLLEGE,G GANESH KUMAR,pacrpoly@gmail.com
127,SRI VIDYA COLLEGE OF ENGINEERING & TECHNOLOGY,MR. N.VENKETESAN,nvenkatesanmtech@gmail.com
128,SATHYABAMA UNIVERSITY,DR T SASIPRABA,deanoffice@sathyabamauniversity.ac.in
129,SRI RAMAKRISHNA INSTITUTE OF TECHNOLOGY,JOTHI K R,jothi.cse@srit.org
130,KALASALINGAM UNIVERSITY,Dr.G.Murugaboopathi,gmurugaboopathi@klu.ac.in
849,ASHOKRAO MANE GROUP OF INSTITUTIONS FACULTY OF ENGINEERING & MANAGEMENT STUDIES ,PROF. V.A.KULKARNI,vak@amgoi.edu.in
131,THIAGARAJAR POLYTECHNIC COLLEGE,B SELVAKUMAR,tptcnptel@gmail.com
132,RAJALAKSHMI ENGINEERING COLLEGE,DR.V.PRASANNA KUMARI,prasannakumari.v@rajalakshmi.edu.in
133,SETHU INSTITUTE OF TECHNOLOGY,Mr T SENTHIL RAJAN,senthilrajant@sethu.ac.in
134,JSPMS RAJARSHI SHAHU COLLEGE OF ENGINEERING,MS S.P.GUDI,contactlibrary@gmail.com
135,RAMAKRISHNA MISSION VIVEKANADA CENTENARY COLLEGE,MR. MANAS MOULIC,manaseng82@gmail.com
136,VELLALAR COLLEGE FOR WOMEN,MS K ARUNPRABHA,arunjeevesh@gmail.com
137,CSI COLLEGE OF ENGINEERING,KETTI,PROF. STALIN ALEX,stalinalexphd@csice.edu.in
138,PANDIAN SARASWATHI YADAV ENGINEERING COLLEGE,BALAMURUGAN E,balapsyec@gmail.com
139,GOVERNMENT COLLEGE OF TECHNOLOGY,DR. MEENA SRINIVASAN,meenasrinivasan@gct.ac.in
140,R D ENGINEERING COLLEGE,MOHIT KUMAR SINGH,er.mksingh@gmail.com
141,SRI VASAVI COLLEGE,RAMYA DEVI R,ramya07devi@yahoo.co.in
142,K S RANGASAMY COLLEGE OF TECHNOLOGY,DR P PREMKUMAR,premkumar@ksrct.ac.in
143,M A M COLLEGE OF ENGINEERING AND TECHNOLOGY,MR. J. INIGO PAPU VINODHAN,spoc.mamcet@gmail.com
144,V H N S N COLLEGE,PAVALA KUMAR B,pavalakumarb@vhnsnc.edu.in
145,G PULLA REDDY ENGINEERING COLLEGE AUTONOMOUS,DR R PRAVEEN SAM,gprecnptelcse@gmail.com
146,JHARKHAND RAI UNIVERSITY,PROF SUDHANSHU MAURYA,sam.sudhanshu@gmail.com
184,BIRLA INSTITUTE OF APPLIED SCIENCES,MR NITIN CHHIMWAL,nitinntl@yahoo.co.in
148,NATIONAL ENGINEERING COLLEGE,MR S CAMMILLUS,cammilus@nec.edu.in
149,ANNAI VAILANKANNI COLLEGE OF ENGINEERING,PROF A RAJA WINSTON,winston-cs@avce.edu.in
150,BHARATH COLLEGE OF ENGINEERING AND TECHNOLOGY FOR WOMEN,MR. J. PHANEENDRA,paneendra.bhagavan@gmail.com
151,GEETHANJALI INSTITUTE OF SCIENCE AND TECHNOLOGY,MS. Y. JAHNAVI,yjahnavi.gist@gmail.com
152,SRI SARADA COLLEGE FOR WOMEN,Ms S GOMATHY,libraryscw@gmail.com
153,PRATHYUSHA ENGINEERING COLLEGE,MS. KANNAMMA SRIDHARAN ,kannamma.sridharan@gmail.com
156,GULZAR GROUP OF INSTITUTES,DR. R. K. MAHESHWARY,director.gsm@ggi.ac.in
157,WILLINGDON COLLEGE,DR. B.V.TAMHANKAR,baputamhankar@gmail.com
158,SITYOG INSTITUTE OF TECHNOLOGY,DHANANJAY KUMAR,rishav007svm@gmail.com
159,SMT KAMALA AND SHRI VENKAPPA M AGADI COLLEGE OF ENGINEERING AND TECHNOLOGY,PROF SHRIKANTH CHIDANANDAPPA JOGAR,shree.ahd@gmail.com
160,PANIMALAR INSTITUTE OF TECHNOLOGY,DR  A  JOSHI,pitithod@gmail.com
161,PANIMALAR ENGINEERING COLLEGE,M S VINMATHI,vinmathis@gmail.com
162,LINGAYA S GVKS INSTITUTE OF MANAGEMENT AND TECHNOLOGY,MS PARVEEN MOR,mor.praveen439@gmail.com
164,DRONACHARYA GROUP OF INSTITUTIONS,ASHWANI KUMAR,ashwani.kumar@gnindia.dronacharya.info
166,DRONACHARYA COLLEGE OF ENGINEERING,DR SRI KRISHAN YADAV,srikrishanyadavdce@gmail.com
167,NAVSAHYADRI EDUCATION SOCIETY S GROUP OF INSTITUTES,ANIKET DILIP PATIL,aniketpatilmtech@gmail.com
168,ADHIYAMAAN COLLEGE OF ENGINEERING,DR D SWAMYDOSS,hod_mca@adhiyamaan.ac.in
170,SCSVMV UNIVERSITY,DR M SENTHIL KUMARAN,nptelspoc.scsvmv@gmail.com
171,COIMBATORE INSTITUTE OF ENGINEERING AND TECHNOLOGY,GAYATHRI DEVI.S,gg.govind2007@gmail.com
172,SREE SASTHA INSTITUTE OF ENGINEERING AND TECHNOLOGY,R PREMKUMAR,ithodssiet@gmail.com
173,GYAN GANGA COLLEGE OF TECHNOLOGY,MR PANKAJ KUMAR JAIN,pankajjain80@gmail.com
174,NATIONAL INSTITUTE OF TECHNOLOGY GOA,DR MODI CHIRAG NAVINCHANDRA,cnmodi@nitgoa.ac.in
175,MAHATMA GANDHI MISSION S INSTITUTE OF BIOSCIENCES AND TECHNOLOGY, Aurangabad,ASST PROF KIRAN RAMESH PAWAR,kiranpawar@mgmibt.com
176,D.K.T.E SOCIETY S TEXTILE & ENGINEERING INSTITUTE ICHALKARANJI,Dr D V Kodavade,dvkodavade@gmail.com
178,TERNA ENGINEERING COLLEGE,MR KISHOR SHAMRAO SAKURE,kishor_sakure@yahoo.com
179,SCHOOL OF ENGINEERING,DR. JACOB ELIAS,jacobcusat@gmail.com
180,AMRUTVAHINI COLLEGE OF ENGINEERING,MILINDKUMAR B VAIDYA,milind.vaidya@avcoe.org
181,SIES GRADUATE SCHOOL OF TECHNOLOGY,Dr  PRADIP P PATIL,spoc_nptel@siesgst.ac.in
182,SCHOOL OF ENGINEERING AND TECHNOLOGY,KAMAL SALUJA,kamalsalu@gmail.com
183,SRM UNIVERSITY - KATTANKULATHUR,DR.RAJENDRAN,librarian@srmuniv.ac.in
185,KNSK COLLEGE OF ENGINEERING,M MAHABOOBA,knskcespoc2015@gmail.com
187,ANNAMACHARYA INSTITUTE OF TECHNOLOGY AND SCIENCES AUTONOMOUS,PROF KADIYALA RAMANA,ramana.it01@gmail.com
188,MAHARANA PRATHAP ENGINEERING COLLEGE,MOHIT KUMAR SRIVASTAVA,mohitsrivastava@mpgi.edu.in
189,MADANAPALLE INSTITUTE OF TECHNOLOGY & SCIENCE,Dr. R. PARTHIBAN,drparthibanr@mits.ac.in
190,SHRI TULJA BHAVANI COLLEGE OF ENGINEERING,S H PAWAR,stbectlibrary@gmail.com
191,RAJIV GANDHI COLLEGE OF ENGINEERING AND TECHNOLOGY,DR K SHANTHA KUMARI,nptelrgcet@rgcetpdy.ac.in
192,BRINDAVAN INSTITUTE OF TECHNOLOGY & SCIENCE,DR.K.NAGARAJU,nagarajudr09@gmail.com
193,FEROZE GANDHI INSTITUTE OF ENGINEERING AND TECHNOLOGY,DR MANISH SAXENA,manish.mohan.saxena@gmail.com
203,VINAYAKA MISSIONS UNIVERISTY /AARUPADAI VEEDU INSTITUTE OF TECHNOLOGY,V.RATTAN KUMAR,rattankumar@avit.ac.in
195,NARASARAOPETA INSTITUTE OF TECHNOLOGY,PROF V V A S LAKSHMI,vvaslakshmi@gmail.com
196,CENTURION UNIVERSITY OF TECHNOLOGY AND MANAGEMENT,PROF PRABHAT K PATNAIK,prabhat.patnaik@cutm.ac.in
197,ASSAM DON BOSCO UNIVERSITY,VIJAY PRASAD,vijay@dbuniversity.ac.in
198,ST. JOSEPH'S COLLEGE OF ENGINEERING & TECHNOLOGY,MR. JACOB P CHERIAN,jacob.p.cherian@sjcetpalai.ac.in
199,SRI VENKATESWARA COLLEGE OF ENGINEERING AND TECHNOLOGY,MR.N. SENDHIL KUMAR,nptel.spoc@svcet.in
200,UJJAIN ENGINEERING COLLEGE,DR SUNIL PUNJABI,sunilpunjabi@iitkalumni.org
201,BABU BANARASI DAS NATIONAL INSTITUTE OF TECHNOLOGY AND MANAGEMENT,DIWAKAR YAGYASEN,dylucknow@gmail.com
202,VIT UNIVERSITY CHENNAI,Prof PRADEEP KUMAR T S,tspradeepkumar@vit.ac.in
204,AMRAPALI GROUP OF INSTITUTES,DHIRAJ UPADHYAY,dhiraj.upadhayay@gmail.com
205,SHRI SANT GADGE BABA COLLEGE OF ENGINEERING AND TECHNOLOGY,PROF.MRS.NEETA ANIL NEMADE,neeta.nemade@gmail.com
206,NORTH WEST GROUP OF ENGINEERING AND TECHNOLOGY,DR. RAJIV KUMAR MAHESHWARY ,rkm@northwest.ac.in
207,AMMINI COLLEGE OF ENGINEERING,WIN WILSON P,win.wilson@ammini.edu.in
208,NETAJI SUBHASH ENGINEERING COLLEGE,DR PARTH SARATHI PAL,nsec.nptel@gmail.com
209,KARNATAK ARTS SCIENCE AND COMMERCE COLLEGE,DR MALLIKARJUN HANGARGE,mhangarge@yahoo.co.in
210,GOSWAMI GANESH DUTTA SANATAN DHARMA COLLEGE KHERI GURNA,PROF ARVINDER KAUR ,arvinderkaurriar@gmail.com
211,GHARDA INSTITUTE OF TECHNOLOGY,MR.BAVESH N. PATEL,librarian@git-india.edu.in
212,M.M. ENGINEERING COLLEGE,DR. S.K. AGGARWAL ,vasusanjeev@yahoo.co.in
213,K. K. WAGH INSTITUTE OF ENGINEERING EDUCATION & RESEARCH,DR. P.K SHAHABADKAR,kkwieertpo@gmail.com
214,NIT KURUKSHETRA,DR.KRISHNAN GOPAL,kgopalnitk@gmail.com
215,ACHARYA INSTITUTE OF TECHNOLOGY,C K MARIGOWDA,marigowda@acharya.ac.in
216,JEPPIAAR ENGINEERING COLLEGE,DR V ANBARASU,anbarasukv@gmail.com
217,SHRI RAM INSTITUTE OF TECHNOLOGY,PROF MAHENDRA KUMAR RAI,mahendrakumar.rai@gmail.com
218,DOLPHIN PG INSTITUTE OF BIO MEDICAL AND NATURAL SCIENCES,DR AASHEESH RAUTRI ,quark6ashu@gmail.com
219,SRI KRISHNA COLLEGE OF TECHNOLOGY,DR R MAHESWAR,r.maheswar@skct.edu.in
220,Y B CHAVAN COLLEGE OF PHARMACY AURANGABAD,DR MOHAMMAD ISMAIL MOUZAM,ybccpanptel@gmail.com
221,SHREE VENKATESHWARA HITECH ENGINEERING COLLEGE,DR R MUTHUKUMAR,rmuthukumar_2004@yahoo.co.in
222,VEL TECH DR.RR & DR.SR TECHNICAL UNIVERSITY,DR.P.SARASU,veltech@vsnl.com
223,MEERUT INSTITUTE OF TECHNOLOGY,DR JYOTIRMAY PATEL,jyotirmaypatelmit@gmail.com
238,GITAM INSTITUTE OF TECHNOLOGY,DR G V K SARMA ,gvksarma@gitam.edu
237,ROLAND INSTITUTE OF TECHNOLOGY,PROF SUNIL KUMAR NAHAK,hodmca@roland.ac.in
236,INDERPRASTHA ENGINEERING COLLEGE,PRIYANKA D GUPTA,priyanka.gupta@ipec.org.in
235,SHRI SANT GAJANAN MAHARAJ COLLEGE OF ENGINEERING,PROF SANDESH D JAIN,sdjain1990@gmail.com
234,ARUMUGAM PILLAI SEETHAI AMMAL COLLEGE,DR N VIJAYANAND,vijayapsac@gmail.com
233,ACROPOLIS TECHNICAL CAMPUS,PROF ATUL AGRAWAL,nptel.atc@acropolis.in
232,PONDICHERRY ENGINEERING COLLEGE,Dr VIJAYALAKSHMI V,vvijizai@pec.edu
231,SIDDAGANGA INSTITUTE OF TECHNOLOGY,DR. R. S. KADADEVARA MATH,dr.rskmutt@gmail.com
230,BADDI UNIVERSITY OF EMERGING SCIENCES AND TECHNOLOGY,JATINDER K SAMYAL,librarian@baddiuniv.ac.in
229,MEPCO SCHLENK ENGINEERING COLLEGE,R SHANTHA SELVA KUMARI,rshantha@mepcoeng.ac.in
228,VISVESVARAYA TECHNOLOGICAL UNIVERSITY,MANJUNATHA B,manjunathb@vtu.ac.in
227,PSGR KRISHNAMMAL COLLEGE FOR WOMEN,GEETHALAKSHMI K.,geethalakshmi@psgrkc.ac.in
226,BANNARI AMMAN INSTITUTE OF TECHNOLOGY,DR. ARULMURUGAN R.,arulmr@bitsathy.ac.in
225,SRI VENKATESWARA COLLEGE OF ENGINEERING,DR KR SANTHA,hodee@svce.ac.in
224,MIT ACADEMY OF ENGINEERING,VANDANA KHANDELWAL,vbkhandelwal@lib.maepune.ac.in
239,R V COLLEGE OF ENGINEERING,PROF. N. K. SRINATH,srinathnk@rvce.edu.in
240,JANSONS INSTITUTE OF TECHNOLOGY,T MEENAKSHI,nptelspoc@jit.ac.in
241,R.M.D. ENGINEERING COLLEGE,DR.D.RUKMANIDEVI,rukmani.ece@rmd.ac.in
242,RMK ENGINEERING COLLEGE,DR K VIJAYA,nptel@rmkec.ac.in
243,MODERN COLLEGE OF ENGINEERING,MRS PRATIBHA D ADKAR,pratibha.adkar@moderncoe.edu.in
244,DARSHAN INSTITUTE OF ENGINEERING AND TECHNOLOGY,DR DIVYANG D VYAS,divyang.vyas@darshan.ac.in
245,UNITED INSTITUTE OF TECHNOLOGY,B. BALAMANO RANJITH,cue@uit.ac.in
246,SRI ESHWAR COLLEGE OF ENGINEERING,PROF P JOHN AGUSTINE,johnaugustine.p@sece.ac.in
247,KAMARAJ COLLEGE,S RAJAN,sr_tuty@yahoo.co.in
248,UNIVERSITY COLLEGE OF SCIENCE,DR.P.S.RAJPUT,drpsrajput83@gmail.com
249,VARDHAMAN COLLEGE OF ENGINEERING,MR N MADHU,nptel.vardhaman@gmail.com
250,VAAGDEVI INSTITUTE OF TECHNOLOGY AND SCIENCE,MR M VENKATA VEERA PRASAD,mvvp.physics@gmail.com
251,SREE BUDDHA COLLEGE OF ENGINEERING,MR  ARUN M,arunmurali86@gmail.com
252,CMR INSTITUTE OF TECHNOLOGY,NAGARATHNA  S R,librarian@cmrit.ac.in
253,SCHOOL OF MANAGEMENT SCIENCES,SHAMIT SRIVASTAVA,shamit@smslucknow.com
254,COLLEGE OF ENGINEERING KOTTARAKKARA,PROF. RENJITH S R,renjisaras9480@gmail.com
255,JAWAHARLAL COLLEGE OF ENGINEERING AND TECHNOLOGY,SCARIA ALEX,scariaalex@gmail.com
256,GANDHI ENGINEERING COLLEGE,PROF. SANTOSH KUMAR SATAPATHY,santhosh.satapathy@gec.edu.in
257,ST PAULS COLLEGE,PROF TEXIN JOSEPH,txnjoseph@gmail.com
258,MAR ATHANASIOS COLLEGE FOR ADVANCED STUDIESTIRUVALLA,PROF BIJU DHARMAPALAN,biju@macfast.org
275,LAXMI INSTITUTE OF COMMERCE AND COMPUTER APPLICATIONS,MS. SINDHU S PANDYA,bca.laxmi@gmail.com
276,VIMAL JYOTHI ENGINEERING COLLEGE,MR JITHIN K JOSE,nptel@vjec.ac.in
277,ABES ENGINEERING COLLEGE,DR HARI OM UPADHYAY,hariom@abes.ac.in
259,N.S.S COLLEGE OF ENGINEERING,DR. PRIYA G DAS,priyadas27@gmail.com
260,TECHNO INDIA, SALT LAKE, WEST BENGAL,PROF SHAUVIK PAUL,paulshauvik@gmail.com
261,BML MUNJAL UNIVERSITY,MR.MADHAVAN KOLAYAMPARAMPATH,madhavan.k@bml.edu.in
278,AJAY KUMAR GARG ENGINEERING COLLEGE,PROF. S. L. KAPOOR,sl_kapoor@yahoo.co.in
279,ALLENHOUSE INSTITUTE OF TECHNOLOGY,HAMMAD MASHKOOR,cs.hammad@allenhouse.ac.in
280,AMBALIKA INSTITUTE OF MANAGEMENT AND TECHNOLOGY,SUBODH KUMAR,subodhkumar@ambalika.in
281,AZAD INSTITUTE OF ENGINEERING AND TECHNOLOGY LUCKNOW,MS NUSRAT FATMA,nfnusrat@gmail.com
282,B N COLLEGE OF ENGINEERING AND TECHNOLOGY,NISHANT SINHA,crg@bncet.ac.in
283,BBS COLLEGE OF ENGINEERING AND TECHNOLOGY,DR C P SINGH,cpsingh0009@gmail.com
284,GOEL INSTITUTE OF TECHNOLOGY AND MANAGEMENT,DR ARUN KUMAR SINGH,aksingh.uptu@gmail.com
285,HINDUSTAN INSTITUTE OF TECHNOLOGY AND MANAGEMENT,MR SARTAJ KHAN,sartaj.khan@sgei.org
286,ITS ENGINEERING COLLEGE,DR O P CHAUDHARY,opchaudharyas@its.edu.in
287,J P INSTITUE OF ENGINEERING AND TECHNOLOGY,PANKAJ AGARWAL,panagr123@gmail.com
288,KANPUR INSTITUTE OF TECHNOLOGY,RAKESH KUMAR PANDEY,rkp@kit.ac.in
262,EGS PILLAY ENGINEERING COLLEGE,PALANI MURUGAN S,palanimurugan@egspec.org
264,COLLEGE OF ENGINEERING PATHANAPURAM,MRS BIJI S,biji.s.sivan@gmail.com
265,GYANMANJARI INSTITUTE OF TECHNOLOGY,PROF KRUNAL KHIRAIYA,kbkhiraiya@gmit.edu.in
266,NALLA MALLA REDDY EDUCATION SOCIETY,DR M SURESH BABU,sureshbabu.cse@nmrec.edu.in
267,K.J.SOMAIYA INSTITUTE OF ENGG. AND INFORMATION TECHNOLOGY,SION,MUMBAI,PROF JYOTI GANESH WADMARE,jyoti@somaiya.edu
268,SIES COLLEGE OF ARTS SCIENCE AND COMMERCE,MS MAHALAXMI NADAR,cmlnadar@gmail.com
269,KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY,JAWAHAR M,kprietlibrary@gmail.com
270,MAR ATHANASIUS COLLEGE OF ENGINEERING,JISHA KURUVILLA P,jishakuruvilla2015@gmail.com
271,OXFORD ENGINEERING COLLEGE,DR. T.N. PRABAKAR,dean@oxfordec.edu.in
272,AWH ENGINEERING COLLEGE,PROF GIREESH T K,hodcs@awhengg.org
289,KRISHNA ENGINEERING COLLEGE,DR A  N MISHRA,an_mishra53@rediffmail.com
290,NORTH INDIA INSTITUTE OF TECHNOLOGY,MANIK GUPTA,manikbapu@gmail.com
291,PRANVEER SINGH INSTITUTE OF TECHNOLOGY,DR. HARSH DEV ,dean@psit.ac.in
292,RAJ KUMAR GOEL ENGINEERING COLLEGE,DR AMRITA MEHARWAL,amrita.1110@gmail.com
293,S D COLLEGE OF ENGINEERING AND TECHNOLOGY,SH ABHISHEK RAI,abhishekraiiet@gmail.com
294,SHRI RAM GROUP OF COLLEGES,MR ASHISH CHAUHAN,hodcssrgc@gmail.com
295,SHRI RAM MURTI SMARAK COLLEGE OF ENGINEERING AND TECHNOLOGY,DIWAKAR UPADHYAY,diwakarupadhyay@srmscet.edu
296,UNITED COLLEGE OF ENGINEERING AND RESEARCH,RAVI PRAKASH CHATURVEDI,rpchaturvedi51@gmail.com
154,NPTEL TESTING,NAVEEN,naveen@nptel.iitm.ac.in
297,JODHPUR INSTITUTE OF ENGINEERING AND  TECHNOLOGY,SANJAY BHANDARI,sanjay.bhandari@jietjodhpur.ac.in
298,SAGI RAMAKRISHNAM RAJU ENGINEERING COLLEGE,DR N GOPALA KRISHNA MURTHY,gopinukala@gmail.com
299,LAXMI INSTITUTE OF TECHNOLOGY SARIGAM,PROF NANDLAL DHANDHUKIA,nand.litec@gmail.com
300,VIDYA PRATISHTHAN'S KAMAL NAYAN BAJAJ INSTITUTE OF ENGINEERING AND TECHNOLOGY,AVINASH JAGANNATH KOKARE,spoc_nptel@vpkbiet.org
301,SWAMI KESHVANAND INSTITUTE OF TECHNOLOGY MANAGEMENT & GRAMOTHAN,PROF. (DR) D.K. SHARMA,dks@skit.ac.in
302,VISHWAKARMA INSTITUTE OF TECHNOLOGY,MUKUND M. KULKARNI,mukund.kulkarni@vit.edu
303,PATNA WOMENS COLLEGE,MS SUSHMITA CHAKRABORTY,computerdepartment@patnawomenscollege.in
304,CHAROTAR UNIVERSITY OF SCIENCE AND TECHNOLOGY,MR NIRAV H BHATT,niravbhatt.it@charusat.ac.in
305,M. A. M. SCHOOL OF ENGINEERING,G. NUSRATH SUMAIYA,nusrathsumaiya@gmail.com
306,K RAMAKRISHNAN COLLEGE OF TECHNOLOGY,MR  S  SYEDAKBAR,akbarkrct@gmail.com
307,HI-TECH INSTITUTE OF ENGINEERING & TECHNOLOGY (HIET),DR. RAJEEV KUMAR MISHRA,bhu.rajeev@gmail.com
308,MARWADI EDUCATION FOUNDATIONS GROUP OF INSTITUTIONS,MR. AMIT D VED,spoc.nptel@marwadieducation.edu.in
309,JSS ACADEMY OF TECHNICAL EDUCATION,MR VIKAS PANCHAL,vikaspanchal@jssaten.ac.in
310,VIVEKANAND ARTS SARDAR DALIPSINGH COMMERCE AND SCIENCE COLLEGE AURANGABAD,MR PRABHAKAR MORE,registrar@vivekanandcollege.edu.in
311,NATIONAL INSTITUTE OF TECHNOLOGY TIRUCHIRAPPALLI,DR M VENKATA KIRTHIGA,mvkirthiga@nitt.edu
312,D.K.M COLLEGE FOR WOMEN (AUTONOMOUS),DR.J. SHANTHI,librariandkmca@gmail.com
313,M S RAMAIAH INSTITUTE OF TECHNOLOGY,PROF PARKAVI A,parkavi.a@msrit.edu
314,KASHI INSTITUTE OF TECHNOLOGY,MR SANGHARSH KUMAR SINGH,sangharsh@kashiit.ac.in
315,MEDHA COLLEGE OF ENGINEERING FOR WOMEN,PROF. RALLA SURESH,rella.suresh@gmail.com
322,DR AMBEDKAR INSTITUTE OF TECHNOLOGY FOR HANDICAPPED,OM HARI,omhari@aith.ac.in
317,VISHWANATHRAO DESHPANDE RURAL INSTITUTE OF TECHNOLOGY,VIJET SWADI,vijetswadi@gmail.com
318,PRIST UNIVERSITY,DR ASHUTOSH DAS,prist.cee@gmail.com
319,SAI TIRUMALA NVR ENGINEERING COLLEGE,DR. J. CHANDRA SEKHAR,jcsekhar9@gmail.com
323,GOVERNMENT ENGINEERING COLLEGE,AZAMGARH,PROF. D.K.SINGH,director@gecazamgarh.ac.in
321,ATRIA INSTITUTE OF TECHNOLOGY,PROF BASAVARAJU M,basavaraju@atria.edu
324,KIET GROUP OF INSTITUTIONS,DR ANIL K AHLAWAT,anil.ahlawat@kiet.edu
325,BANSAL INSTITUTE OF ENGINEERING & TECHNOLOGY,MR SUMIT KUMAR  GUPTA,er.guptasumit@gmail.com
326,MADAN MOHAN MALAVIYA UNIVERSITY OF TECHNOLOGY,DR SARVPAL SINGH,spsingh@mmmut.ac.in
327,TRUBA INSTITUTE OF ENGINEERING AND INFORMATION TECHNOLOGY,PROF MANOJ TYAGI,manoj.tyagi@trubainstitute.ac.in
328,MOTI BABU INSTITUTE OF TECHNOLOGY,SANJEET KUMAR,contact@sanjeetkumar.in
329,SHRI SHANKARACHARYA TECHNICAL CAMPUS,DR R N PATEL,sstc.spoc@gmail.com
330,PRASAD V POTLURI SIDDHARTHA INSTITUTE OF TECHNOLOGY,MR A VANAMALA KUMAR,vanamalakumar.a@pvpsiddhartha.ac.in
331,PRINCE SHRI VENKATESHWARA PADMAVATHY ENGINEERING COLLEGE,P  ASHOK,ashokp2k4@gmail.com
332,INDORE INSTITUTE OF SCIENCE AND TECHNOLOGY,DR RAJEEV G VISHWAKARMA,rajeev.vishwakarma@indoreinstitute.com
333,AGNI COLLEGE OF TECHNOLOGY,DR. S. PRABAKAR,stanleay@gmail.com
334,VIDYA VIKAS EDUCATION TRSUTS UNIVERSAL COLLEGE OF ENGINEERING,PROF. SUJEET MISHRA,sujit.mishra@universal.edu.in
335,HALDIA INSTITUTE OF TECHNOLOGY,PROF SIRAJ DATTA,Dattasiraj@gmail.com
336,KAMLA NEHRU INSTITUTE OF TECHNOLOGY,PROF  DEEPENDRA SINGH,deependra_knit@yahoo.com
368,ANNAI VELANKANNI COLLEGE,MR C I RAJESH,cirajesh08@gmail.com
367,ADITYA SILVER OAK INSTITUTE OF TECHNOLOGY,MR KOUSHIK GARAIN,koushikgarain.gn@socet.edu.in
366,"MIT COLLEGE OF ENGINEERING
",DR. SUCHITRA A. KHOJE,suchitra.khoje@mitcoe.edu.in
365,PROF RAM MEGHE COLLEGE OF ENGINEERING AND MANAGEMENT,MRS SUPRIYA A BEJALWAR,prmceamlibrary@gmail.com
364,INTERNATIONAL CENTRE OF EXCELLENCE IN ENGINEERING  AND MANAGEMENT,PROF ANANDRAO B HUMBE,humbeanand@gmail.com
363,SARASWATI COLLEGE OF ENGINEERING,SHARADDHA C SUBHEDAR,shraddhasubhedar23@gmail.com
362,L&T INSTITUTE OF TECHNOLOGY,MRS.NIMITA RAUT,nimita.raut@larsentoubro.com
337,CHHATRAPATI SHIVAJI INSTITUTE OF TECHNOLOGY,PRABHAS KUMAR GUPTA,prabhashgupta@csitdurg.in
338,DIT UNIVERSITY,DR RITIKA,hod.mca@dituniversity.edu.in
339,TRUBA COLLEGE OF SCIENCE AND TECHNOLOGY,PROF ATUL KUMAR SHRIVASTAVA,atul.shrivastava@trubainstitute.ac.in
340,SHRI RAM MURTI SMARAK WOMEN'S COLLEGE OF ENGG.& TECH.,MR ANKUR KUMAR,ankur.kumar@srmswcet.ac.in
341,SHIVAJIRAO S JONDHALE COLLEGE OF ENGINEERING &TECHNOLOGY,PROF. PRAVIN P. ADIVAREKAR,engineerpravin2008@gmail.com
342,UNIVERSITY COLLEGE OF ENGINEERING PANRUTI,MR. M. GNANAPRAKASH,gnanam.au@gmail.com
343,SREE RAMA ENGINEERING COLLEGE,PROF. S CHAKRI SRIDHAR,chakri.sreedhar@gmail.com
344,D.A.V INSTITUTE OF ENGINEERING & TECHNOLOGY (DAVIET),DR. JAGJIT MALHOTRA,jmalhotra292@gmail.com
345,GOVERNMENT COLLEGE OF ENGINEERING  KALAHANDI,PROF  AJIT KUMAR PATTANAIK,ajitpuce@gmail.com
346,LACHOO MEMORIAL COLLEGE OF SCIENCE & TECHNOLOGY (AUTONOMOUS),SH RAJPAL SINGH RAJPUROHIT,sidhartrajpal77@gmail.com
347,LOKMANYA TILAK COLLEGE OF ENGINEERING,DR. JAYESH J DANGE,jayesh_dange@rediffmail.com
348,P A COLLEGE OF ENGINEERING AND TECHNOLOGY,DR D GANESHKUMAR,pacetnptel@gmail.com
349,PILLAI INSTITUTE OF INFORMATION TECHNOLOGY ENGINEERING MEDIA STUDIES AND RESEARCH,PROF. ARUN SHRIDHARAN PILLAI,profarun@mes.ac.in
361,YASHWANTRAO CHAVHAN INSTITUTE OF SCIENCE,SHASHIKANT SHINDE,shashikshinde@gmail.com
378,HARCOURT BUTLER TECHNOLOGICAL INSTITUTE,PROF. NARENDRA KOHLI,kohli.hbti@gmail.com
359,FR.C.RODRIGUES ISTITUTE OF TECHNOLOGY,Dr.Nitesh Yelve,spoc.nptel@fcrit.ac.in
360,ST.FRANCIS INSTITUTE OF TECHNOLGY,DR KEVIN NORONHA,kevinkurkal@gmail.com
358,ATHARVA COLLEGE OF ENGINEERING,PRAJAKTA BOROLE,gala.dipa000@gmail.com
357,PACE INSTITUTE OF TECHNOLOGY & SCIENCES,DR T RAMA CHAITHANYA,chaitanya_tr@pace.ac.in
356,PUNE INSTITUTE OF COMPUTER TECHNOLOGY,PROF. RAJNARAYAN SHRIWAS,rnshriwas@gmail.com
355,S. K. SOMAIYA DEGREE COLLEGE OF ARTS, SCIENCE AND COMMERCE,DR. SANGEETHA KOHLI ,nptel_spoc.sksac@somaiya.edu
354,DAYALBAGH EDUCATIONAL INSTITUTE,PROF. D. BHAGWAN DAS,dbhagwandas@gmail.com
353,G. PULLAIAH COLLEGE OF ENGINEERING AND TECHNOLOGY,Mr M GRIDHAR KUMAR,placementofficer@gpcet.ac.in
352,RK UNIVERSITY,FALGUN N.ADROJA,falgun.adroja@rku.ac.in
351,SYDENHAM INSTITUTE OF MANAGEMENT STUDIES AND RESEARCH AND ENTREPRENEURSHIP EDUCATION,MR PAVAN C PATIL ,pavansimsree@gmail.com
350,SHIVAJIRAO S JONDHLE POLYTECHNIC, ASANGAON,PROF. SHUVETA CHANCHALANI,0935Principal@msbte.com
369,RAJ KUMAR GOEL INSTITUTE OF TECHNOLOGY FOR WOMEN,DR J P NAVANI,jpnavani@rkgitw.edu.in
370,GIRIJANANDA CHOWDHURY INSTITUTE OF MANAGEMENT AND TECHNOLOGY,SOURAV NATH,spoc.gimttezpur@gmail.com
371,POTTI SRIRAMULU CHALAVADI MALLIKHARJUNA RAO COLLEGE OF ENGINEERING AND TECHNOLOGY,PROF. A. PATANJALI SASTRI ,cse.hod@pscmr.ac.in
372,PANKAJ LADDHAD INSTITUTE OF TECHNOLOGY AND MANAGEMENT STUDIES,PROF S R SAWALAKHE,plitsrs@gmail.com
373,LOVELY PROFESSIONAL UNIVERSITY,PROF SUNAINA KHURANA,academic_staffcollege@lpu.co.in
374,GURU GOBIND SINGH COLLEGE OF PHARMACY,DR. ROHIT DUTT,drrohitdatt23@gmail.com
375,VEL TECH HIGH TECH DR RANGARAJAN DR SAKUNTHALA ENGINEERING COLLEGE,MR PRADEEP KATTA,pradeepkatta@velhightech.com
376,ARULMURUGAN COLLEGE OF ENGINEERING,MR. KRISHNA KANT PRASAD,acecsehod@gmail.com
377,VISHWAKARMA INSTITUTE OF INFORMATION TECHNOLOGY,MRS. KIRTI H. WANJALE,Kirti.wanjale@viit.ac.in
379,UNIVERSITY INSTITUTE OF ENGINEERING & TECHNOLOGY,DR ANJU DIXIT,dixitanju00@gmail.com
380,SHRI SHANKARACHARYA INSTITUTE OF PROFESSIONAL MANAGEMENT & TECHNOLOGY,DR ALOK KUMAR JAIN,principal@ssipmt.com
381,B.S.A. COLLEGE OF ENGINEERING & TECHNOLOGY,DR. ASEEM CHANDEL,aseemchandel@gmail.com
382,AKSHAYA COLLEGE OF ENGINEERING AND TECHNOLOGY,P DAMODHARAN,damodharan@acetcbe.edu.in
383,MALLA REDDY ENGINEERING COLLEGE FOR WOMEN,B.V.S.P.PAVAN KUMAR,tpomrecw@gmail.com
384,WALCHAND COLLEGE OF ENGINEERING,SANGLI,DR S D RUIKAR,ruikarsachin@gmail.com
385,SAGAR INSTITUTE OF SCIENCE TECHNOLOGY AND RESEARCH SISTECR,PROF MAYANK GUPTA,nptel.sistecr@gmail.com
386,CHRIST COLLEGE OF ENGINEERING AND TECHNOLOGY,G.KARTHI,ithod@christcet.edu.in
387,ST.THOMAS COLLEGE OF ENGINEERING & TECHNOLOGY,DR.MRS.SHUKLA SANYAL,shukla06.ss@gmail.com
388,UNIVERSAL COLLEGE OF ENGINEERING & TECHNOLOGY,SHARMA NAVEENKUMAR,naveensharma31588@yahoo.com
389,PRAGATI ENGINEERING COLLEGE,MR.M.V.RAJESH,nptel_spoc@pragati.ac.in
390,MADHA ENGINEERING COLLEGE,MR.V.SRINIVASAN,srinivasanmba1952@gmail.com
391,LOYOLA INSTITUTE OF TECHNOLOGY,MR.KUMAR,litprincipaloffice@gmail.com
392,VIVEKANANDHA INSTITUTE OF INFORMATION AND MANAGEMENT STUDIES,MS. J. KOKILAVANI ,viimsnptel@gmail.com
393,VIDYA COLLEGE OF ENGINEERING,MR.RAM KUMAR PATHAK,vce@vidya.edu.in
394,DAYANANDA SAGAR UNIVERSITY,DR J C DAVID ,library@dsu.edu.in
395,MAHARISHI ARVIND INSTITUTE OF ENGINEERING AND TECHNOLOGY,DR MANISH BHARGAVA,manishbhargava257@gmail.com
396,RAJAS INTERNATIONAL INSTITUTE OF TECHNOLOGY FOR WOMEN,DR. DIVYA THANGA,divyathanga@riit.cc
397,BHARATHIDASAN ENGINEERING COLLEGE,MR. C. SIVALINGAM,library@bec.ac.in
398,SREE SAKTHI ENGINEERING COLLEGE,MS. SHYAMALA G,shyamala@sreesakthi.edu.in
413,HRIT GROUP OF INSTITUTIONS,MR SANDEEP YADAV,sandyadov24@gmail.com
399,GURU JAMBHESHWAR UNIVERSITY OF SCIENCE AND TECHNOLOGY,DR. VINOD KUMAR,vinu@gjust.org
400,KUMARAGURU COLLEGE OF TECHNOLOGY,R RAFFIK,kctnptelspoc@gmail.com
401,BABA INSTITUTE OF TECHNOLOGY AND SCIENCES,G ASWAN KUMAR,aswangera@bitsvizag.com
402,SAHYADRI COLLEGE OF ENGINEERING AND MANAGEMENT,MR.DUDDELA SAI PRASHANTH,dsaip13@gmail.com
403,GLBAJAJ GROUP OF INSTITUTIONS,DR MEENU GUPTA,dr.meenu2@gmail.com
404,RAJ KUMAR GOEL INSTITUTE OF TECHNOLOGY,MR.PAWAN KUMAR VERMA,pvmnnit@gmail.com
405,K.L.E COLLEGE OF ENGINEERING & TECHNOLOGY,PROF.SATISH S BHOJANNAVAR,satish@klecet.edu.in
406,SRI RAMAKRISHNA ENGINEERING COLLEGE,DR SUNDARARAJ K,nptel@srec.ac.in
407,VELAMMAL ENGINEERING COLLEGE,DR S SRINATH,drsrinath.eee@velammal.edu.in
408,RVS TECHNICAL CAMPUS-COIMBATORE,DR.R.PARIMELAZHAGAN,rvslibrarianfoe@gmail.com
409,AL-AMEEN INSTITUTE OF INFORMATION SCIENCES,MOHAN RAJ C S,mohanrajcs@gmail.com
410,AMRITA VISHWA VIDYAPEETHAM UNIVERSITY,R PRAMOD,ase.pramod@gmail.com
411,FEDERAL INSTITUTE OF SCIENCE AND TECHNOLOGY (FISAT),RESHMI R,reshmiajay@fisat.ac.in
412,COLLEGE OF ENGINEERING,VADAKARA,DR MATHEW B V,spoc.cev@gmail.com
414,BFIT GROUP OF INSTITUTION,MR ARVINDER SINGH HIRA,ashira1982@gmail.com
451,SIR PADAMPAT SINGHANIA UNIVERSITY,AMAN JAIN,amanjain@spsu.ac.in
415,GEETANJALI INSTITUTE OF TECHNICAL STUDIES,MR ANURAG PALIWAL,paliwal_rajasthan@yahoo.com
416,GMR INSTITUTE OF TECHNOLOGY,MR. A.V. RAMANA,venkataramana.a@gmrit.org
417,RUNGTA COLLEGE OF ENGINEERING AND TECHNOLOGY,RAIPUR,PROF. RAJKUMAR PATRA ,rajkumar.patra@rungta.ac.in
418,MEDI-CAPS UNIVERSITY,INDORE,DR GYANENDRA SINGH LODHA,gyanendralodha55@gmail.com
419,NALSAR UNIVERSITY OF LAW, HYDERABAD,SHRI. I.S.R.B. SAI SUBRAHMANYAM,subrahmanyam@nalsar.ac.in
625,PONJESLY COLLEGE OF ENGINEERING,EDWIN CHANDRA S,echandran@yahoo.com
421,NALLA NARASIMHA REDDY EDUCATION SOCIETY'S GROUP OF INSTITUTIONS- SCHOOL OF ENGINEERING,MS. L. VANDANA,vandanakiran.lingampally@gmail.com
422,ACROPOLIS INSTITUTE OF TECHNOLOGY & RESEARCH,MR PRAVEEN BHANODIA,praveenbhanodia@acropolis.in
423,SHREE SWAMI ATMANAND SARASWATI INSTITUTE OF TECHNOLOGY,Prof. Paresh M. Patel,pareshp317@gmail.com
424,SAVEETHA SCHOOL OF ENGINEERING,MR C RAJAGOPAL,rajagopal@saveetha.com
425,VIVEKANANDHA INSTITUTE OF ENGINEERING & TECHNOLOGY FOR WOMEN,KARTHIKEYAN C,vietwnptel@gmail.com
426,SADGURU GADAGE MAHARAJ COLLEGE, KARAD,DR. S. R. SAWANT,sambhajisawant@gmail.com
427,KARMAYOGI ENGINEERING COLLEGE,PROF DIPAK V BHOSALE,deepbhosale507@gmail.com
430,CENTRAL INSTITUTE OF PLASTIC ENGINEERING & TECHNOLOGY,MRS PARVIN KHAN,cipetlibrary0522@gmail.com
431,BHILAI INSTITUTE OF TECHNOLOGY, DURG,Dr  Arpana Rawal,arpana.rawal@gmail.com
432,INDUS INSTITUTE OF TECHNOLOGY & MANAGEMENT,MR SANJAY SINGH,ssingh_707@rediffmail.com
433,BHABHA INSTITUTE OF TECHNOLOGY,PROF AMOD TIWARI,amodtiwari@gmail.com
434,BHABHA COLLEGE OF ENGINEERING,PROF RAJENDRA KUMAR DWIVEDI,profrkdwivedi@gmail.com
435,D S INSTITUTE OF TECHNOLOGY & MANAGEMENT,MR SUSHANT JHINGRAN,sushantjhingran@gmail.com
436,RAMESHWARAM INSTITUTE OF TECHNOLOGY & MANAGEMENT,MR HARIKESH PANDEY,ritm358@gmail.com
437,BHARAT INSTITUTE OF TECHNOLOGY,MR ARVIND RAJA,hoden@bitmeerut.co.in
438,SUNRISE INSTITUTE OF ENGINEERING TECHNOLOGY & MANAGEMENT,MISS KOMAL GAUR,gaurkomal13@gmail.com
439,GRAPHIC ERA HILL UNIVERSITY,MR PRABHAT KUMAR,prabhat.bcet@gmail.com
428,WOMEN INSTITUTE OF TECHNONLOGY,MS SUNITA CHANDEL,vidyarthisunita@gmail.com
429,INSTITUTE OF ENGINEERING & MANAGEMENT,PROF RATNA CHAKRABARTY,ratna.chakrabarty@iemcal.com
274,SONA COLLEGE OF TECHNOLOGY,DR.J.SENTHILKUMAR,jsenthil10@gmail.com
441,VIGNAN'S INSTITUTE OF INFORMATION TECHNOLOGY,PUDI SEKHAR,pudisekhar1@gmail.com
442,GUDLAVALLERU ENGINEERING COLLEGE,E. VARGIL KUMAR,gecnptel@gmail.com
443,PYDAH COLLEGE OF ENGINEERING,LANGOJU SRI M K V PRASAD,nptel.spoc@pydah.co.in
444,S.P.B. PATEL ENGINEERING COLLEGE,PROF. HIRAL PARMAR,hiral.parmar@saffrony.ac.in
445,PARTHIVI COLLEGE OF ENGINEERING AND MANAGEMENT,AVINASH SINGH,avinash1.parthivi@gmail.com
446,INTEGRATED ACADEMY OF MANAGEMENT AND TECHNOLOGY,NEELAM YADAV,neelam.yadav@inmantec.edu
447,J K INSTITUTE OF APPLIED PHYSICS & TECHNOLOGY,DR ASHISH KHARE,nptel.jk@gmail.com
448,JAIPURIA INSTITUTE OF MANAGEMENT,DR SHUBHENDRA SINGH PARIHAR,shubhendra.parihar@jaipuria.ac.in
449,IMS ENGINEERING COLLEGE,DR AVDHESH GUPTA,avdhesh.gupta@imsec.ac.in
450,K.N.G.D MODI ENGINEERING COLLEGE,MR OMENDRA SINGH BANSLA,nptel@kngdmec.ac.in
452,GOVT WOMEN'S COLLEGE,DR KUMARI NIMISHA,kumari.nimisha.gwc@gmail.com
453,RUNGTA COLLEGE OF ENGINEERING & TECHNOLOGY,Kapil Kumar Nagwanshi,kapilk.nagwanshi@rungta.ac.in
454,NPTEL LOCALCHAPTER,NLC TEST SPOC,nlcdummyspoc@gmail.com
455,ORIENTAL INSTITUTE OF SCIENCE & TECHNOLOGY,PROFESSOR SANJAY KUMAR SHARMA,oisthodcse@oriental.ac.in
456,BABU BANARSI DAS INSTITUTE OF TECHNOLOGY,DR AMIT SINGHAL,amitsinghal.cs@bbdit.edu.in
457,SWARNANDHRA INSTITUTE OF ENGINEERING AND TECHNOLOGY,DR. T. MURALI MOHAN,nptel.siet@gmail.com
458,ADITYA ENGINEERING COLLEGE,K ASHOK KUMAR,spoc.aec@gmail.com
459,AKRG COLLEGE OF ENGINEERING & TECHNOLOGY,MR YALANATI AYYAPPA,akrgcet.nptel@gmail.com
460,PEC UNIVERSITY OF TECHNOLOGY,ANKIT YADAV,ankityadav@pec.ac.in
461,LAKIREDDY BALI REDDY COLLEGE OF ENGINEERING,MR.K.R.L.PRASAD,nptellbrce@gmail.com
462,THANGAL KUNJU MUSALIAR COLLEGE OF ENGINEERING,ADARSH S,adarsh1982@tkmce.ac.in
463,UNIVERSITY OF ENGINEERING & MANAGEMENT (UEM),PROF. SUKALYAN GOSWAMI,sukalyan.goswami@iemcal.com
464,RISE KRISHNA SAI PRAKASAM GROUP OF INSTITUTIONS,M.JAGADISH,risenptel@gmail.com
465,INDUS UNIVERSITY,PROF HANSA SHINGRAKHIA,hansashingrakhia.ec@indusuni.ac.in
466,QIS COLLEGE OF ENGINEERING AND TECHNOLOGY,DR. SRINIVAS  RAO NALLURI,librarianqis2007@gmail.com
467,KLE TECHNOLOGICAL UNIVERSITY,PROF. JAYALAKSHMI G. NARAGUND,jaya_gn@bvb.edu
468,"SRI SIVANI COLLEGE OF ENGINEERING,DR. G. RAJENDRA KUMAR,rajendramadhavi@gmail.com
469,MARATHWADA MITRA MANDAL'S COLLEGE OF ENGINEERING,ANJALI SOLANKE,anjalisolanke@mmcoe.edu.in
470,IIMT COLLEGE OF ENGINEERING,BRAJESH RAJ,brajeshraj_gn@iimtindia.net
471,ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY,R.SRINIVAS,acet.nptelspoc@gmail.com
472,ANU BOSE INSTITUTE OF TECHNOLOGY,SATYAM NAIDU PANDRANKI,librarian.abit@gmail.com
473,JAYAWANT INSTITUTE OF COMPUTER APPLICATIONS,MRS. SUNANDA SHARAD PHULARI,jicalibrary@gmail.com
474,SHRI SHIVAJI COLLEGE,DR ROHIDAS NITONDE,rsnitonde@gmail.com
475,ALIGARH COLLEGE OF ENGINEERING & TECHNOLOGY,MR AJIT KUMAR CHANSAURIYA,ajitchansauriya@gmail.com
476,LAKSHMI NARAIN COLLEGE OF TECHNOLOGY & SCIENCE,DR AMITBODH UPADHYAYA,amitbodhupadhyaya@gmail.com
477,RAJA BALWANT SINGH ENGINEERING TECHNICAL CAMPUS,DR B D K PATRO,bdkpatro@rediffmail.com
478,BETHESDA INSTITUTE OF TECHNOLOGY AND SCIENCES,MR HEMANT GUPTA,spocnptelbits@gmail.com
479,DREAM INSTITUTE OF TECHNOLOGY,DR ANKUSH GHOSH,ankushghosh@gmail.com
480,MODERN INSTITUTE OF ENGINEERING & TECHNOLOGY,DR. ASESH SAHA,hod_me@mietcollege.org
481,DR. B.R. AMBEDKAR INSTITUTE OF TECHNOLOGY,DR SHRABANI MALLICK,shrabani.reek@gmail.com
482,R.M.K. COLLEGE OF ENGINEERING AND TECHNOLOGY,DR K A SELVAKUMARAN, nptel_spoc@rmkcet.ac.in
520,BHILAI INSTITUTE OF TECHNOLOGY, NEW RAIPUR,PROF ASHISH UPADHYAY,ashish.spocbitr@gmail.com
539,MCKV INSTITUTE OF ENGINEERING,PROF  DR  PREMANANDA JANA  ,p.janamckvie@gmail.com
537,MES COLLEGE OF ENGINEERING,K P BALACHANDRAN,nptel@mesce.ac.in
538,JAI NARAIN COLLEGE OF TECHNOLOGY,DR. KRISHNA KUMAR GUPTA,kkg.manit@gmail.com
483,B.P. PODDAR INSTITUTE OF MANAGEMENT AND TECHNOLOGY,MR. PALLAB KUMAR BHAUMIK,pallabkumarbhaumik123@gmail.com
484,MALLABHUM INSTITUTE OF TECHNOLOGY,MR. PRIYATOSH JANA,priyatoshjana@gmail.com
485,UNIVERSITY OF ENGINEERING AND MANAGEMENT,SANDIP DAS,sandip.das@iemcal.com
486,MVJ COLLEGE OF ENGINEERING,DR. M. PAULINE,hod_cse@mvjce.edu.in
487,MATOSHRI COLLEGE OF ENGINEERING AND RESEARCH CENTRE NASHIK,MCERCNASHIK,Mahendra.adhav@gmail.com
488,USHA RAMA COLLEGE OF ENGINEERING AND TECHNOLOGY,PROF  KELOTHU NARESH,eeehod@usharama.in
489,J.N.N INSTITUTE OF ENGINEERING,MR SIVAJI D.,sivajid@jnn.edu.in
490,BHARATI VIDYAPEETH COLLEGE OF ENGINEERING,PROF B W BALKHANDE,balkhandeakshay@gmail.com
491,SRINIVASA INSTITUTE OF ENGINEERING AND TECHNOLOGY,MR M V SAMUDRAM,samudrammv@gmail.com
492,CHAUDHARY CHARAN SINGH UNIVERSITY MEERUT,DR J A SIDDIQUI,jamal_siddiqui2004@yahoo.co.in
493,NATIONAL INSTITUTE OF TECHNOLOGY,PROF. SUCHISMITA CHINARA,suchismita@nitrkl.ac.in
494,PADMANAVA COLLEGE OF ENGINEERING,ATISH KUMAR PATRA,atishpatra08@gmail.com
495,FACULTY OF ENGINEERING TECHNOLOGY AND RESEARCH,PROF PRATIK D SOLANKI,nptel.fetr@gmail.com
496,SRI JAGADGURU CHANDRASHEKARANATHA SWAMIJI INSTITUTE OF TECHNOLOGY (SJCIT),DR. K. M. RAVIKUMAR,hodece@sjcit.ac.in
497,JAYPEE UNIVERSITY OF INFORMATION TECHNOLOGY,DR PRADEEP KUMAR SINGH,pksingh.juit@gmail.com
498,P.S.R.POLYTECHNIC COLLEGE,SANKARASUBRAMANIAN M,psrpcnptel@psr.edu.in
499,SAINTGITS COLLEGE OF ENGINEERING,Dr CHERIAN PAUL ,cherian.paul@saintgits.org
500,STANLEY COLLEGE OF ENGINEERING AND TECHNOLOGY FOR WOMEN,C KISHOR KUMAR REDDY,ckishorkumar@stanley.edu.in
501,SRI BASAVESHWARA INSTITUTE OF TECHNOLOGY,SRI H N HALAPPA,halappa.hn@gmail.com
502,SHRI VISHNU ENGINEERING COLLEGE FOR WOMEN,DR POKKULURI KIRAN SREE,nptel@svecw.edu.in
503,MES COLLEGE MARAMPALLY,INDU SUSSAN VARGHESE,indukaleekkal10@gmail.com
504,BUDGE BUDGE INSTITUTE OF TECHNOLOGY,PROF  KRISHNENDU RARHI,comsoc.coordinator@bbit.edu.in
505,SAI VIDYA INSTITUTE OF TECHNOLOGY,PROF.VIKRAM ADITYA.J. M,vikramaditya.jm@saividya.ac.in
506,ST JOSEPH ENGINEERING COLLEGE,MR PRATHVIRAJ N,elearning@sjec.ac.in
507,MAHARAJ VIJAYARAM GAJAPATHI RAJ COLLEGE OF ENGINEERING,KONA UMA MAHESH YADAV,librarian.mvgr@mvgrce.edu.in
508,GLOBAL INSTITUTE OF TECHNOLOGY,DR ASHISH VASHISTHA,ashish.vashistha@gitjaipur.com
541,DR. SUBHASH TECHNICAL CAMPUS,PROF CHETAN J SHINGADIYA,ceit_hod@drsubhashtech.edu.in
540,ST. THOMAS INSTITUTE FOR SCIENCE & TECHNOLOGY,PREETHI ELIZABETH IYPE,preethikoshy@gmail.com
526,EASTERN ACADEMY OF SCIENCE & TECHNOLOGY,PROF SAUMYAKANTA SARANGI,saumyasarangi27@gmail.com
509,BHARAT COLLEGE OF ENGINEERING,PROF ANKUR SHARMA,asharma@bharatedu.co.in
510,JB INSTITUTE OF TECHNOLGY,PROF. AMIT DAS,amitdas01@gmail.com
511,MANGALAM COLLEGE OF ENGINEERING,MR BENPHIL C MATHEW,benphil.mathew@mangalam.in
512,KALYANI GOVT. ENGINEERING COLLEGE,MAHADEB RANA,rana.mahadeb@gmail.com
513,DR. B. C. ROY ENGINEERING COLLEGE,DR. MANIK MANDAL,manik.mandal@bcrec.ac.in
514,R S R RUNGTA COLLEGE OF ENGINEERING & TECHNOLOGY,MR MOHD SHAJID ANSARI,shajidavis@gmail.com
515,G D RUNGTA COLLEGE OF ENGINEERING & TECHNOLOGY,MR GURUDATTA VERMA,gurudatta.verma@gmail.com
516,SASI INSTITUTE OF TECHNOLOGY & ENGINEERING,MR  KATAKAM SRINU,library@sasi.ac.in
517,ST. JOHN COLLEGE OF ENGINEERING AND TECHNOLOGY,MR DHIRAJ K BHANDARKAR,dhirajb@sjcet.co.in
518,SHANKERSINH VAGHELA BAPU INSTITUTE OF TECHNOLOGY,LOKAPAVANA H. M.,lokapavana.hebbale@bapugkv.ac.in
519,CHHATTISGARH ENGINEERING COLLEGE,MR. SURENDRA KUMAR CHANDRAKAR,surendrasam31@gmail.com
548,APEX INSTITUTE OF ENGINEERING AND TECHNOLOGY,MR. VIMAL AGARWAL,dean@apexcollege.in
521,ARVIND GAVALI COLLEGE OF ENGINEERING,MR HINGMIRE VISHAL SHARAD,vs.hingmire@gmail.com
522,TRUBA COLLEGE OF ENGINEERING & TECHNOLOGY,RITU TANDON,ritu.bansal@trubainstitute.ac.in
523,BVC COLLEGE OF ENGINEERING,R N V VISHNU MURTHY,ravipati.naniprince@gmail.com
524,MOHAMED SATHAK A.J. COLLEGE OF ENGINEERING,KAVITHA SIVAKUMAR,Nptelspoc@msajce-edu.in
525,CAMELLIA SCHOOL OF ENGINEERING & TECHNOLOGY,DR JAYANTA GOPE,jayanta.gope.1983@ieee.org
527,BANSAL COLLEGE OF ENGINEERING,SUMIT THAKUR,bcenptel@gmail.com
528,G L BAJAJ INSTITUTE OF TECHNOLOGY AND MANAGEMENT,DR ARUN KUMAR BISWAL,arun.biswal@glbitm.org
529,MALLA REDDY ENGINEERING COLLEGE (AUTONOMOUS),SHAIK JAKEER HUSSAIN,iiic@mrec.ac.in
530,SHRI CHHATRAPATI SHIVAJI MAHARAJ COLLEGE OF ENGINEERING,RASKAR RAHUL BHAUSAHEB,rahulraskar14@gmail.com
531,PSIT COLLEGE OF HIGHER EDUCATION,DR. SHIVANI KAPOOR,deanbba@psit.ac.in
532,SAGAR INSTITUTE OF RESEARCH & TECHNOLOGY,DR NEELESH KUMAR JAIN,neeleshcmc@gmail.com
533,SCHOOL OF MANAGEMENT SCIENCES,VARANASI,DR ADITYA KUMAR GUPTA,aditya.guptas@gmail.com
534,IES COLLEGE OF TECHNOLOGY,DEEPTI DAVE,nptel@iesbpl.ac.in
535,BRAINWARE GROUP OF INSTITUTIONS,MR PULAK PATRA,pulakmath11@gmail.com
542,SEEMANT INSTITUTE OF TECHNOLOGY,MR. SUMIT JOSHI,joshigauta@gmail.com
536,DR. G.Y. PATHRIKAR COLLEGE OF COMPUTER SCIENCE AND INFORMATION TECHNOLOGY,DR MAJHARODDIN MUMTAJMIYAN KAZI,gypc.nptel.localchapter@gmail.com
543,MAHARANI LAKSHMI AMMANI COLLEGE FOR WOMEN,USHA T.,usha.middha@mlacw.org
544,DWARKADAS J.SANGHVI COLLEGE OF ENGINEERING,MRS VISHAKHA KELKAR,spoc.djsce@gmail.com
545,SHRI MADHWA VADIRAJA INSTITUTE OF TECHNOLOGY AND MANAGEMENT,MANOJ T,nptellc@sode-edu.in
546,GURU NANAK INSTITUTE OF TECHNOLOGY,MR ANIMESH KAR,head_mca.gnit@jisgroup.org
547,PROUDHDEVARAYA INSTITUTE OF TECHNOLOGY,DR. N. NAGARAJA,nagphysics@gmail.com
604,ANNASAHEB CHUDAMAN PATIL COLLEGE OF ENGINEERING,MR. DADABHAI D. PATIL.,librarian@acpce.ac.in.
550,R R INSTITUTE OF MODERN TECHNOLOGY,MR TARUN KUNAL SINGH,tarunkunalsingh@gmail.com
551,SURENDRA GROUP OF INSTITUTIONS,MR VIVEK GUPTA,nptel.sgi@gmail.com
552,SHRI BHAGWAN COLLEGE OF PHARMACY,MR GADADE DIPAK DILIP,deepscpn@gmail.com
553,FUTURE INSTITUTE OF ENGINEERING AND MANAGEMENT,PROF.  DEBASHIS  CHAKRABORTY  ,debashisc77@gmail.com
557,GOVERNMENT MEDICAL COLLEGE BHAVNAGAR,DR CHINMAY SHAH,cjshah79@yahoo.co.in
555,SHAH & ANCHOR KUTCHHI ENGINEERING COLLEGE,MS PRANALI WAGH,sakec.spoc@gmail.com
556,COLLEGE OF ENGINEERING & MANAGEMENT, KOLAGHAT,DR. DILIP KUMAR GAYEN  ,dilipgayen@cemk.ac.in
558,P.T.R. COLLEGE OF ENGINEERING & TECHNOLOGY,MR  M JOHN BASHA,ptrcetnptel@gmail.com
559,SHRI GURU RAM RAI INSTITUTE OF TECHNOLOGY & SCIENCE,SACHIN NAUTIYAL,sachin.nautiyal@sgrrits.org
560,K.S.R. COLLEGE OF ENGINEERING,MR. MURUGESAN,sysmurugesh@gmail.com
561,MALLA REDDY COLLEGE OF ENGINEERING & TECHNOLOGY, SECUNDERABAD,Dr.S. Srinivasa Rao,ssrao.atri@gmail.com
562,SURENDRA INSTITUTE OF ENGINEERING & MANAGEMENT, SILIGURI (SIEM),DR. DEEPAYAN SHOME,deepayanshome@rediffmail.com
563,UKF COLLEGE OF ENGINEERING AND TECHNOLOGY,DR. M. S. SENTHIL SARAVANAN,bhatranitt@gmail.com
564,TECHNO INDIA AGARTALA,DR. DIBAKAR DEB,deb.dibakar@tiaedu.org
565,NEOTIA INSTITUTE OF TECHNOLOGY MANAGEMENT AND SCIENCE,DR. ASHOKE KUMAR BASU,ashokekumarbasu@gmail.com
566,S.N.R. SONS COLLEGE,DR. ANNA SARO VIJENDRAN,annasarovijendran@gmail.com
568,KONKAN GYANPEETH. COLLEGE OF ENGINEERING, KARAJAT,PROF. P.R.BHOSALE,popatbhosale08@gmail.com
567,CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY,PRODDATUR,MR N G V SATYA KUMAR,nptelcbit@gmail.com
569,SATYA COLLEGE OF ENGINEERING & TCHNOOGY,MR JITENDRA KUMAR,jitendrak@satyaedu.org
570,DHANALAKSHMI COLLEGE OF ENGINEERING,DR PRADEEP KUMAR A R,hod.mech@dce.edu.in
571,SHRI MATA VAISHNO DEVI UNIVERSITY,DR AMIT KANT PANDIT,nptelsmvdu@gmail.com
572,GURU GOBIND SINGH EDUCATIONAL SOCIETYS TECHNICAL CAMPUS,MAHMOOD ALAM,mahmoodalam.mech@gmail.com
573,ST.THOMAS COLLEGE OF ENGINEERING & TECHNOLOGY, KANNUR,AJANA V K,ajanav@stthomaskannur.ac.in
660,D. Y. PATIL COLLEGE OF ENGINEERING,RAHUL RAMESH KALE,spoc.dypcoe@gmail.com
575,SHREE GANPATI INSTITUTE OF TECHNOLOGY,MR. BHANU PRATAP SINGH,Bhanu.pratapcs@sgit.ac.in
576,NATIONAL INSTITUTE OF TECHNOLOGY MEGHALAYA,DR. A. DANDAPAT,anup.dandapat@nitm.ac.in
577,VISWAJYOTHI COLLEGE OF ENGINEERING AND TECHNOLOGY,RAJESH CHERIAN ROY,rajeshcherian11@gmail.com
578,DEV BHOOMI GROUP OF INSTITUTIONS,MR. SHUBHASHISH GOSWAMI,sugh.goswani@gmail.com
579,ANAND INSTITUTE OF INFORMATION SCIENCE,MR. PRAVIN PATEL,mca501owner@gtu.edu.in
580,MARATHWADA MITRA MANDAL'S INSTITUTE OF TECHNOLOGY,MR CHAITANYA RAJENDRA MANKAR,chaitanya.mankar@mmit.edu.in
581,K.R. GOURI AMMA COLLEGE OF ENGINEERING FOR WOMEN,ARUN KUMAR,ak3064@gmail.com
582,K.C. COLLEGE OF ENGINEERING & MANAGEMENT STUDIES & RESEARCH,HARI RAJAI,kctpo15@gmail.com
708,GOVT. COLLEGE OF ENGINEERING & TEXTILE TECHNOLOGY,CHANDAN SINHA ROY,gcettb.nptel@gmail.com
584,ZAKIR HUSSAIN COLLEGE OF ENGINEERING AND TECHNOLOGY,PROF. ARSHAD UMAR,arshad_umar@rediffmail.com
585,DEVIPRASAD GOENKA MANAGEMENT COLLEGE OF MEDIA STUDIES,DR KUMARDATT A GANJRE,director@dgmcms.org.in
586,HEERA COLLEGE OF ENGINEERING AND TECHNOLOGY (HCET),ANAND MICHAEL VIJAY,anandmichael007@gmail.com
587,P.S.R.ENGINEERING COLLEGE,D ARUN SHUNMUGAM,psrecnptel@psr.edu.in
588,TECHNO INDIA - BATANAGAR,MR ALOK KUMAR SHRIVASTAV,alok5497@gmail.com
589,TECHNO INDIA COLLEGE OF TECHNOLOGY,MR SWAGATA PAUL,techsp123@gmail.com
590,SILIGURI INSTITUTE OF TECHNOLOGY,PROF. MANAS SAHA  ,manassaha77@yahoo.com
591,MEGHNAD SAHA INSTITUTE OF TECHNOLOGY,PROF. (DR.) TIRTHANKAR DATTA,ask.tdatta@gmail.com
592,ABS ACADEMY OF SCIENCE, TECHNOLOGY & MANAGEMENT,MR. ASIS KUMAR SARKAR  ,spoc.abs@gmail.com
593,GOVERNMENT ENGINEERING COLLEGE, CHAIBASA,SUDIPTA CHAKRABORTY,nptellocal@gmail.com
594,GOVERNMENT ENGINEERING COLLEGE, RAMGARH,DR. NAVONIL BOSE,navonilbose@gmail.com
595,GOVERNMENT ENGINEERING COLLEGE, DUMKA,MR RANADEEP DEY,ranadeep37.dey@gmail.com
596,GOVERNMENT POLYTECHNIC SILLI,MR. UTPAL KUMAR PAUL,utpal16nov@gmail.com
597,GOVERNMENT COLLEGE OF ENGINEERING & RESEARCH,DR DILIP RAMBHAU PANGAVHANE,drpangavhane@yahoo.co.in
598,JCT COLLEGE OF ENGINEERING AND TECHNOLOGY,MR K SIVAKUMAR,sivakumar.k@jct.ac.in
599,AKS UNIVERSITY,DR KAUSIK MUKHERJEE,km466430@gmail.com
600,OM DAYAL GROUP OF INSTITUTIONS,MS. SHARANYA GHOSH,sharanyaghosh3@gmail.com
601,ABS ACADEMY OF POLYTECHNIC,MR. ASIS KUMAR SARKAR,spoc.abs@gmail.com
602,TRP ENGINEERING COLLEGE,MR. S.VICTOR SOOSAI IRUDAYA RAJ,trp.placement@gmail.com
603,ANDHRA LOYOLA INSTITUTE OF ENGINEERING AND TECHNOLOGY,MR  S  KISHOR BABU,hod.it.aliet@gmail.com
605,NORTH MALABAR INSTITUTE OF TECHNOLOGY,MR ANU JACOB PAUL,viceprincipal@nmitkerala.ac.in
606,A.G.PATIL INSTITUTE OF TECHNOLOGY,MR. AMEY DOSHI,amey.doshi@agpit.edu.in
617,JIJAMATA MAHAVIDYALAYA, BULDHANA,MR. UMESH R. GADHAVE,sachin_eight@rediffmail.com
607,INDRAPRASTHA INSTITUTE OF INFORMATION TECHNOLOGY,DR. ANUBHA  GUPTA,nptel-spoc@iiitd.ac.in
608,DHIRAJLAL GANDHI COLLEGE OF TECHNOLOGY,DR S VENKATESH,spoc.nptel@dgct.ac.in
609,ANNASAHEB DANGE COLLEGE OF ENGINEERING & TECHNOLOGY,N.L. NARASIMHA REDDY,nln_aero@adcet.in
610,MVSR ENGINEERING COLLEGE,DR AKHIL KHARE,khare_cse@mvsrec.edu.in
611,VELALAR COLLEGE OF ENGINEERING AND TECHNOLOGY,DR.S.SADESH,sadesh_vcet@yahoo.com
612,CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY,HYDERABAD,Dr C Srikanth Reddy,spoc.cbit@gmail.com
613,NORTHERN INDIA ENGINEERING COLLEGE,MD SAQUIB FARAZ,saquib.faraz@niecdelhi.ac.in
614,RAMACHANDRA COLLEGE OF ENGINEERING,MR. EKAMBARAM,rceenptel@gmail.com
615,ROORKEE COLLEGE OF ENGINEERING,ABHINAV BHATNAGAR,rceroorkee@gmail.com
616,AVVAIYAR COLLEGE OF ENGINEERING & TECHNOLOGY FOR WOMEN,MR. K. MURUGAN,murugan.acetw@gmail.com
618,S S TEGNOOR DEGREE COLLEGE,DR. JYOTHI R TEGNOOR,sstegnoor1@gmail.com
619,SHIVAJIRAO S.JONDHLE COLLEGE OF ENGINEERING & TECHNOLOGY,Mr. Pravin P. Adivarekar,engineerpravin2008@gmail.com
620,JIS COLLEGE OF ENGINEERING,Debasree Mitra  ,debasree.mitra2005@gmail.com
621,IDEAL INSTITUTE OF ENGINEERING,Mr Ashim Kumar Bhaumik,asbhaumik0@gmail.com
622,ARYABHATTA COLLEGE OF ENGINEERING & RESEARCH CENTER,MR. ASHISH GWALANI,spoc.aryabhatta@gmail.com
623,R K COLLEGE OF ENGINEERING,DR. M. N. V. KIRAN BABU,hodcse.rkce@gmail.com
624,EASWARI ENGINEERING COLLEGE,MR R PRASANNA,prasannamtech86@gmail.com
626,BHARAT INSTITUTE OF ENGINEERING AND TECHNOLOGY,V SATYANARAYANA,bietspocnptel@gmail.com
627,LOYOLA INSTITUTE OF TECHNOLOGY AND SCIENCE,D.SHIBU,shibu.cse@lites.edu.in
628,M.V.S.R.ENGINEERING COLLEGE,Dr.AKHIL KHARE,khare_cse@mvsrec.edu.in
629,COLLEGE OF ENGINEERING ROORKEE,HEMANTH KATIYAR,coerlibrarian@gmail.com
630,SINHGAD INSTITUTE OF TECHNOLOGY AND SCIENCE,SANDIP B SHROTE,sandip.shrote@gmail.com
631,KARPAGAM UNIVERSITY,Mr T RAMESH,your.ramesh83@gmail.com
632,PRIYADARSHINI COLLEGE OF ENGINEERING,DR. ASMITA D. DESHPANDE,spocpcenagpur@gmail.com
633,VELAGAPUDI RAMAKRISHNA SIDDHARTHA ENGINEERING COLLEGE,S.RAJESH,rssingam99@gmail.com
634,THE NEOTIA UNIVERSITY,Dr Pulok Pattanayak,pulok.pattanayak@tnu.in
635,SECAB INSTITUTE OF ENGINEERING & TECHNOLOGY,Shreekant Salotagi,shreekant2486@gmail.com
636,A.D. PATEL INSTITUTE OF TECHNOLOGY,PARESH R MODHA,ee.paresh@adit.ac.in
637,DON BOSCO COLLEGE,REMYA.P,remya.kelothillam@gmail.com
638,HINDUSTHAN COLLEGE OF ENGINEERING & TECHNOLOGY,Dr PRADHAPRAJ,nmpradhap@gmail.com
639,KAKINADA INSTITUTE OF ENGINEERING & TECHNOLOGY,K.RAJESH,rajesh_american@yahoo.co.in
640,KAKINADA INSTITUTE OF ENGINEERING & TECHNOLOGY II,CH.SUNAD,sunad.chadalavada@gmail.com
641,KAKINADA INSTITUTE OF ENGINEERING & TECHNOLOGY FOR WOMEN,S.V.KRISHNA REDDY,kietprincipaloffice@gmail.com
642,INSTITUTE OF PHARMACY, PSIT KANPUR,Dr.PRANAY WAL,pranaywal@psit.ac.in
643,P.S.R.RENGASAMY COLLEGE OF ENGINEERING FOR WOMEN,Dr C BALASUBRAMANIAN,nptelpsrr@psrr.edu.in
644,ACHARIYA COLLEGE OF ENGINEERING TECHNOLOGY,A ALBERT ALEXE,albertalex.acet@achariya.org
645,ST.ANN'S COLLEGE OF ENGINEERING & TECHNOLOGY,Y MASTANAIH NAIDU,mastan.talkin@gmail.com
646,ADITYA COLLEGE OF ENGINEERING,A.SRIDHAR ,sriadityanptelspoc@gmail.com
670,ANIL NEERUKONDA INSTITUTE OF TECHNOLOGY & SCIENCES,S SURESH,suresh@anits.edu.in
647,BANKURA UNNAYANI INSTITUTE OF ENGINEERING,Subrata Pan  ,subratapan.it@buie.ac.in
648,KM. MAYAWATI GOVT. GIRLS POST GRADUATE COLLEGE,Dr.DINESH C.SHARMA,kmggpgc.nptel@gmail.com
649,JYOTHY INSTITUTE OF TECHNOLOGY,Dr. RUDRESH KUMAR K.J,rudreshkumarkj@gmail.com
650,K. RAMAKRISHNAN COLLEGE OF ENGINEERING,D.KARAL MARX,karalnptelspoc@gmail.com
651,BAPATLA ENGINEERING COLLEGE,YELISETTY MURALI KRISHNA,murali.bec21@gmail.com
652,NOORUL ISLAM CENTRE FOR HIGHER EDUCATION,Dr.M.DEV ANAND,niucisetm@gmail.com
653,KCG COLLEGE OF TECHNOLOGY,Dr K Vijayaraja,drvijayarajakengaiah@gmail.com
654,G.H. RAISONI INSTITUTE OF ENGINEERING & TECHNOLOGY,SNEHA POKHARKAR,sneha.pokharkar@raisoni.net
655,BPHE SOCIETY'S AHMEDNAGAR COLLEGE,AHMEDNAGAR,MAHADEO SHRIDHAR JADHAV,mjadhavnature@gmail.com
656,COLLEGE OF APPLIED SCIENCE NADAPURAM,SINDHU C S,sindhucsihrd@gmail.com
657,VIGNANA BHARATHI INSTITUTE OF TECHNOLOGY,T.NARASIMHA REDDY,nptelvbit@gmail.com
658,PAD. DR. VITHALRAO VIKHE PATIL FOUNDATION'S COLLEGE OF PHYSIOTHERAPY,Dr.SUVARNA S.GANVIR,suvarna.ganvir@gmail.com
659,SHRI GULABRAO DEOKAR COLLEGE OF ENGINEERING,JALGAON,PARAG YASHWANT PATIL,paragpatil.sgdcoe@gmail.com
661,MUMBAI COLLEGE OF HOTEL MANAGEMENT AND CATERING TECHNOLOGY,Prajakta Mahadik,info@mumbaicollege.com
662,CHENNAI MEDICAL COLLEGE HOSPITAL & RESEARCH CENTRE,M ISMAIL,cmchrc.nptel@gmail.com
663,TKM INSTITUTE OF TECHNOLOGY,SAJI KUNJUMON,sajikunjumon@gmail.com
664,RAJIV GANDHI UNIVERSITY OF KNOWLEDGE TECHNOLOGIES,RAKESH ROSHAN,roshan@rgukt.ac.in
665,KONGU ARTS AND SCIENCE COLLEGE,S VIJAYAKUMAR,sakthiveluvijayakumar@gmail.com
666,M.A.M COLLEGE OF ENGINEERING,JOSHUA ARUL KUMAR R,tap@mamce.org
667,NARULA INSTITUTE OF TECHNOLOGY,Mr Jayanta Pal,head_cse.nit@jisgroup.org
668,ADITYA INSTITUTE OF TECHNOLOGY AND MANAGEMENT,YUGANDHAR DASARI,yugndasari@gmail.com
669,FLORA INSTITUTE OF TECHNOLOGY,PUNE,Lata Rajendra More ,morelata736@gmail.com
671,VIGNANA BHARATHI INSTITUTE OF TECHNOLOGY,HYDERABAD,GANTA SRINIVASA RAO,libraryvbit@gmail.com
672,UTTARAKHAND OPEN UNIVERSITY,Dr.SUMIT PRASAD,sprasad@uou.ac.in
673,TRINITY COLLEGE OF ENGINEERING,RAHUL V R,trinitynptel@gmail.com
674,MATRUSRI ENGINEERING COLLEGE,DR PALLAVI KHARE,pallavi3386@gmail.com
675,SRI SAIRAM INSTITUTE OF TECHNOLOGY,DR.T.N.M.THARINNI MAI,libraryssit0716@gmail.com
739,JERUSALEM COLLEGE OF ENGINEERING,MR. NAGISETTY SRIDHAR,sridharnagisetty@gmail.com
676,KINGS ENGINEERING COLLEGE,Mr SUTHAGAR S,susjou@gmail.com
677,ASHOKA INSTITUTE OF TECHNOLOGY AND MANAGEMENT,Er ASHIM DEV,info@ashokainstitute.com
678,ARMY INSTITUTE OF TECHNOLOGY,VAISHALI INGALE,vingale@aitpune.edu.in
679,GOVERNMENT COLLEGE OF ENGINEERING, SATARA,BHUSHAN SUKUMAR YELURE,bhushanyelure2008@gmail.com
680,SRI PADMAVATI MAHILA VISVAVIDYALAYAM (WOMEN'S UNIVERSITY),Dr K USHA RANI ,nptel.spmvv.localchapter@gmail.com
681,A.P.SHAH INSTITUTE OF TECHNOLOGY,SACHIN H MALAVE,shmalave@apsit.org.in
682,S. A. ENGINEERING COLLEGE,Dr.V.JAIGANESH,draj@saec.ac.in
683,JEPPIAAR MAAMALLAN ENGINEERING COLLEGE,SHAKTHIMURUGAN K H ,shakthimurugankh@gmail.com
684,PAAVAI ENGINEERING COLLEGE,Dr.A.SUPHALAKSHMI,peccsehod@paavai.edu.in
685,THAKUR COLLEGE OF ENGINEERING AND TECHNOLOGY,Mr Anil K Vasoya,vasoyaanil32@gmail.com
686,RAJARSHI SHAHU COLLEGE OF ENGINEERING,BULDANA,P.S.GAWANDE,psgawande2007@gmail.com
687,MAULI GROUP OF INSTITUTION'S, COLLEGE OF ENGINEERING AND TECHNOLOGY,RAVIKIRAN G DESHMUKH,mgicoet.nptel@gmail.com
688,G.H.RAISONI INSTITUTE OF ENGINEERING AND MANAGEMENT, JALGAON,SUSHANT SHANKAR SAMLETI,sushant.samleti@raisoni.net
689,JAIHIND COLLEGE OF ENGINEERING,DNYANESHWAR NATHA WAVHAL ,dnyaneshwar.wavhal@gmail.com
690,CAMELLIA INSTITUTE OF TECHNOLOGY,MADHYAMGRAM,ARPITA BASU,basuarpita11@gmail.com
691,NEW HORIZON COLLEGE OF ENGINEERING,Dr.R.ELUMALAI,hodeee.nhce@gmail.com
692,VIDYA VIKAS INSTITUTE OF ENGINEERING AND TECHNOLOGY,NITESH K A,niteshneetu91@gmail.com
693,AVINASHILINGAM INSTITUTE FOR HOME SCIENCE AND HIGHER EDUCATION FOR WOMEN,Dr. Mrs. S.SIVAKUMARI,nptelavinuty@gmail.com
694,DR. JIVRAJ MEHTA INSTITUTE OF TECHNOLOGY,ANIRUDHA SINGH,anirudha.singh@djmit.ac.in
695,RRS COLLEGE OF ENGINEERING AND TECHNOLOGY,Dr. SHAIK MEERAVALI,shaik5045@gmail.com
696,YASHODA TECHNICAL CAMPUS, SATARA,SUJIT SHEDAGE,sbs_mech@yes.edu.in
697,SWARNANDHRA COLLEGE OF ENGINEERING AND TECHNOLOGY,V.SATYA KISHORE,scetnptel@gmail.com
698,AURORA'S ENGINEERING COLLEGE,M.SURESH BABU,venkatasureshbabu.mupparaju@gmail.com
699,M.KUMARASAMY COLLEGE OF ENGINEERING,Dr.P.SUDHAKAR,hodit@mkce.ac.in
700,SIDDHARTH INSTITUTE OF ENGINEERING & TECHNOLOGY,M.AFSAR ALI,afsarmail123@gmail.com
701,SPECTRUM COLLEGE OF TECHNOLOGY,BABU G,babu@sct.ac.in
702,GANDHINAGAR INSTITUTE OF TECHNOLOGY,Prof Ashish R Majithiya,ashish.majithiya@git.org.in
703,PARVATHANENI BRAHMAYYA SIDDHARTHA COLLEGE OF ARTS & SCIENCE,VENKATA RAMANA VADLAMUDI,ramanavadlamudi@yahoo.com
704,SRI SUKHMANI INSTITUTE OF ENGINEERING & TECHNOLOGY,DERABASSI,KAPIL KUMAR   ,kapilkumarphy@gmail.com
705,CENTRAL UNIVERSITY OF KARNATAKA,Dr.V.SANDEEP,sandeep@cuk.ac.in
706,SHIVALIK COLLEGE OF ENGINEERING,KULDEEP RAWAT,kuldeeprawat.fmesce@gmail.com
707,MVN UNIVERSITY,Dr RAJEEV RATAN,rajeevarora@mvneducation.com
761,COLLEGE OF ENGINEERING, PUNE,DR. AJIT S. SONAWANE,librarian@mescoepune.org
709,ACS COLLEGE OF ENGINEERING,DR T.SENTHIL KUMARAN,senthilvts@gmail.com
710,BAPURAO DESHMUKH COLLEGE OF ENGINEERING,SEWAGRAM,Dr  R S  MANGRULKAR,rsmangrulkar@gmail.com
711,SHRI SHIVAJI COLLEGE OF ARTS, COMMERCE AND SCIENCE,AKOLA,DR ASHISH S RAUT,iqacasraut@gmail.com
712,ADI SHANKARA INSTITUTE OF ENGINEERING & TECHNOLOGY,RAJANI S H,rajani.ae@adishankara.ac.in
713,NEHRU INSTITUTE OF TECHNOLOGY,Mrs R GOWTHAMANI,nitnptel2016@gmail.com
714,QUANTUM SCHOOL OF TECHNOLOGY,MR RAVI KUMAR GOEL,ravigoel.me@quantumeducation.in
715,SARADA KRISHNA HOMOEOPATHIC MEDICAL COLLEGE,DR. SUMAN SANKAR A.S.,dissert02@gmail.com
716,SAMANVAY PRATISHTHAN'S INSTITUTE OF KNOWLEDGE COLLEGE OF ENGINEERING,MR ASHISH P SHASTRI,ashishshastri.mech@gmail.com
717,NAVODAYA INSTITUTE OF TECHNOLOGY,RAICHUR,DR.P.RATHNAKUMAR,hodmech.nit@navodaya.edu.in
718,PUNJABI UNIVERSITY, PATIALA,Dr Vishal Goyal,vishal.pup@gmail.com
719,B.S.ABDUR RAHMAN UNIVERSITY,DR C THARINI,bsaunptel@gmail.com
720,DR.N.G.P. INSTITUTE OF TECHNOLOGY,DR.S.JAGANATHAN,jaganngp@gmail.com
721,JAI BHARATH COLLEGE OF MANAGEMENT & ENGINEERING TECHNOLOGY,MINU MATHEW,minu.30may@gmail.com
722,LENDI INSTITUTE OF ENGINEERING & TECHNOLOGY,MR. ANJI REDDY.V,anjisoftware@hotmail.com
723,SURESH DESHMUKH COLLEGE OF ENGINEERING,MR. A.V. BHOYAR,aniket_bhoyar@rediffmail.com
732,ARUNA VIDYA ARTS & SCIENCE COLLEGE,MRS R GAYATHRI,rgayathrianand@gmail.com
724,GRAPHIC ERA UNIVERSITY,PRAVEEN KALURA,praveenkalura@gmail.com
725,THE ICFAI UNIVERSITY (FST),DR.RAKESH PANDEY,rakesh.pandey@iudehradun.edu.in
726,BANGABASI COLLEGE,DR PARTHA GHOSH,ghosh_partha25@rediffmail.com
727,CHANNABASAVESHWARA INSTITUTE OF TECHNOLOGY,PRADEEP V.,pradeep.v@cittumkur.org
728,GOVERNMENT COLLEGE OF ENGINEERING,TIRUNELVELI,DR. A. KRISHNAVENI,krishnaveni@gcetly.ac.in
729,SRR & CVR GOVT. DEGREE COLLEGE,DR G VENKATA RAO,srrcvrgdc.nptel@gmail.com
730,AHALIA SCHOOL OF ENGINEERING & TECHNOLOGY,MR SATHISH KUMAR R K,sathishrk1982@yahoo.com
731,OM COLLEGE OF ENGINEERING,AMIT S MANIKRAO,amit.manikrao@gmail.com
733,V.V.P. INSTITUTE OF ENGINEERING & TECHNOLOGY, SOLAPUR,MR RAHUL B DIGGE,drahul22@gmail.com
734,SUPREME KNOWLEDGE FOUNDATION GROUP OF INSTITUTIONS,DR. NAVONIL BOSE,spoc.nptel@skf.edu.in
735,SANJAY GHODAWAT GROUP OF INSTITUTIONS,NILESH VIJAY SABNIS,sabnis.nv@sginstitute.in
736,ALWAR INSTITUTE OF ENGINEERING & TECHNOLOGY ,PROF. VISHWADEEPAK SINGH BAGHELA,principal@alwariet.com
737,INSTITUTE OF ENGINEERING & TECHNOLOGY -ALWAR,NEERAJ SANGAL,deanplacement@ietgroupalwar.com
738,VNR VIGNANA JYOTHI INSTITUTE OF ENGINEERING &TECHNOLOGY,K RAVIKUMAR,ravikumar.prist.cee@gmail.com
740,JEC GROUP OF COLLEGES,DR BHARAT BHUSHAN JAIN,drbharatjainjec@gmail.com
741,SHERWOOD COLLEGE OF MANAGEMENT,NATENDRA SAXENA,scm@sherwoodindia.in
742,G. NARAYANAMMA INSTITUTE OF TECHNOLOGY AND SCIENCE (FOR WOMEN),DR K RAGINI,nptel@gnits.ac.in
743,PSG COLLEGE OF ARTS & SCIENCE,L.THARA,kltharavijay@gmail.com
744,VIDYA ACADEMY OF SCIENCE & TECHNOLOGY,SIVADASAN E T,sivadasan@vidyaacademy.ac.in
745,SHRI GOVINDRAO MUNGHATE ARTS & SCIENCE COLLEGE,DR. ABHAY B. SOLUNKE,vidyakurkheda@rediffmail.com
746,GIRIJABAI SAIL INSTITUTE OF TECHNOLOGY ,RAVI B.K.,ravibk4@gmail.com
747,PACIFIC SCHOOL OF ENGINEERING,PROF. MIRAL R.THAKKER,t.miral.pse@gmail.com
748,TULSIRAMJI GAIKWAD-PATIL COLLEGE OF ENGINEERING & TECHNOLOGY,MUKUL PANDE ,mukulpande@tgpcet.com
749,GAYATRI VIDYA PARISHAD COLLEGE OF ENGINEERING,DR. SANJAY KUMAR,sanjay_kumar74@gvpce.ac.in
750,K S R INSTITUTE FOR ENGINEERING AND TECHNOLOGY,Ms K J UMA,ksrietnptel@gmail.com
751,SHIVAJI MAHAVIDYALAYA, RENAPUR,MR. MOHAMMAD HANIF ISMAIL SHAIKH,shivajicollegerenapur@gmail.com
752,DHOLE PATIL COLLEGE OF ENGINEERING,PROF. NIKHIL LAXMAN LANDGE,nikhillandage@gmail.com
753,MAHATMA GANDHI MISSION COLLEGE OF ENGINEERING & TECHNOLOGY,PROF. P.J. SALUNKE,pjsalunke11@gmail.com
754,BHEEMANNA KHANDRE INSTITUTE OF TECHNOLOGY ,SUNIL K. SANGAME,sunsang2003@gmail.com
755,MAHAVEER INSTITUTE OF TECHNOLOGY & SCEINCE,SWAPNA BOHRA,tpo@mitsjadan.ac.in
756,GOVT. MODEL ENGINEERING COLLEGE,JAIMON JACOB,jaimon@mec.ac.in
757,KAKATIYA INSTITUTE OF TECHNOLOGY & SCIENCE,DR. M.VEERA REDDY,librarykitsw@gmail.com
758,SAROJ MOHAN INSTITUTE OF TECHNOLOGY,MR. AVIK DUTTA,avikdutta1985@gmail.com
759,ST. MARY'S GROUP OF INSTITUTIONS HYDERABAD,DR. MANDADI.MEHER SRINIVAS RAO,principald0@stmarysgroup.com
760,M.E.S CHAITANYA P.U. COLLEGE,RANJIT HEGDE,chaitanyapu@gmail.com
762,SREE VIDYANIKETHAN INSTITUTE OF MANAGEMENT,Dr J MURTHY,dearmurthymba@gmail.com
763,KG REDDY COLLEGE OF ENGINEERING & TECHNOLOGY,M.SAIDIREDDY,hod.cse@kgr.ac.in
764,JYOTHI ENGINEERING COLLEGE,DR ADARSH N GOKUL,librarian@jecc.ac.in
765,V.V.VANNIAPERUMAL COLLEGE FOR WOMEN (AUTONOMOUS),MRS P SUGANTHI,vvvcmba@gmail.com
766,VIDHYAPEETH INSTITUTE OF SCIENCE & TECHNOLOGY,DEEPAK KUMAR,deepak.kirar@gmail.com
767,STELLA MARIS COLLEGE (AUTONOMOUS),MS. M.MAHALAKSHMI,smcnptel@stellamariscollege.edu.in
768,BONAM VENKATA CHALAMAYYA ENGINEERING COLLEGE,M.AKHIL KUMAR,librarian.bvce@bvcgroup.in
769,BAPUJI INSTITUTE OF ENGINEERING & TECHNOLOGY,MR.CHANDAN V.,chandan008@gmail.com
770,AISSMS INSTITUTE OF INFORMATION TECHNOLOGY,MS. PUSHPA VITTHAL HIRAVE,pvhirave@gmail.com
771,QIS INSTITUTE OF TECHNOLOGY,NANNURI SURESH,nannurisj@gmail.com
772,MAHARAJA SURAJMAL INSTITUTE,DR  AMIT CHOUDHARY,amitchoudhary@msi-ggsip.org
773,MLR INSTITUTE OF TECHNOLOGY,DR.KVSN RAMA RAO,hodit@mlrinstitutions.ac.in
774,SHAMBHUNATH INSTITUTE OF ENGINEERING & TECHNOLOGY,PRASHANT SRIVASTAVA,prashants.iiita@gmail.com
775,CNR ARTS & SCIENCE COLLEGE,C.VIJAY BHASKAR REDDY,cnr.piler@gmail.com
776,B.V. BHOOMARADDI ARTS, SCIENCE COMMERCE U.G.&P.G. COLLEGE,UMAKANTH DESHMUKH,bvbdc1960@gmail.com
777,GAYATRI VIDYA PARISHAD SCHOOL OF ENGINEERING,PROF.D. SARITHA,deansa@gvptc.edu.in
778,PERIYAR UNIVERSITY,PROF. DR.V.R.PALANIVELU,profdrvrpnptel@gmail.com
779,ANANTRAO PAWAR COLLEGE OF ENGINEERING & RESEARCH,PROF DEEPA BAPOO MANE,deepabmane@gmail.com
780,ALAGAPPA UNIVERSITY,DR.G.RAMALINGAM,alunanoram@gmail.com
781,KONGU ENGINEERING COLLEGE,DR.P.NAVANEETHAKRISHNAN,pnk.mech@kongu.edu
782,ITM COLLEGE OF ENGINEERING,Dr. A.M. MUKE,spocitmcoe@gmail.com
783,SNJB'S LATE SAU. KANTABAI BHAVARLALJI JAIN COLLEGE OF ENGINEERING ,DIPESH AGARWAL,agrawal.drcoe@snjb.org
784,DNYANDEEP SHIKSHAN PRASARAK MANDAL ARTS, COMMERCE & SCIENCE COLLEGE ,DR. T. D. KOSE,t.kose@rediffmail.com
785,SANAKA EDUCATIONAL TRUSTS GROUP OF INSTITUTIONS INSTITUTE OF ENGINEERING & INDUSTRIAL TECHNOLOGY,DR.SWATI GHOSH,sanakanptel2016@gmail.com
786,SENGAMALA THAYAAR EDUCATIONAL TRUST WOMENS COLLEGE,A ADHISELVAM,adhiselvam.a@gmail.com
787,INDIAN INSTITUTE OF INFORMATION TECHNOLOGY, DESIGN AND MANUFACTURING, KANCHEEPURAM,Dr VENKATA TIMMARAJU MALLINA,vtmallina@iiitdm.ac.in
788,SYED AMMAL ENGINEERING COLLEGE,Dr N KARTHIKEYAN,nptel@syedengg.ac.in
789,RTC INSTITUTE OF TECHNOLOGY,MR. RAJESH SINGH  ,singhraj12345@gmail.com
790,PRIYADARSHINI INDIRA GANDHI COLLEGE OF ENGINEERING  ,PROF. SAGAR  SHYAM  MOTDHARE,sagar_motdhare@yahoo.com
791,NAMDEORAO POREDDIWAR COLLEGE OF ENGINEERING & TECHNOLOGY,GAURAV UDAY BUDDHAWAR,buddha.gaurav@gmail.com
792,KARMAVIR DADASAHEB KANNAMWAR COLLEGE OF ENGINEERING,DR. S.P.KHANDAIT,spoc.kdkcengp@gmail.com
793,PEOPLES UNIVERSITY,ANJUL RAI,anjulrai@puibm.in
794,THEIVANAI AMMAL COLLEGE FOR WOMEN,MS. B.SRIDEVI,tacwnptel@gmail.com
795,BABA FARID GROUP OF INSTITUTIONS,SAHIL BHARDWAJ,iamsahil.b@gmail.com
796,CMR COLLEGE OF ENGINEERING & TECHNOLOGY,MR.M.SURESH,msuresh@cmrcet.org
797,K.L.N.COLLEGE OF INFORMATION TECHNOLOGY,AGHILA,aghila.r@klncit.edu.in
798,S.S. AGRAWAL INSTITUTE OF ENGINEERING & TECHNOLOGY, NAVSARI,MR MAHESHKUMAR K MANGUKIYA,maheshmangukiya@gmail.com
799,GOVERNMENT ENGINEERING COLLEGE, KOZHIKODE,DR. K. MEENAKSHY,meenakshymoorthy@gmail.com
800,G H PATEL COLLEGE OF ENGINEERING & TECHNOLOGY,PROF MUKESHKUMAR M BHESANIYA,mukeshbhesaniya@gcet.ac.in
801,JEPPIAAR SRR ENGINEERING COLLEGE,MR.R ARUMUGAM,srrlibrary1@gmail.com
802,SRINIVASA RAMANUJAN INSTITUTE OF TECHNOLOGY,PRANEEL KUMAR PERURU,praneel.cse@srit.ac.in
803,THEJUS ENGINEERING COLLEGE,MRS. NEENU P .A.,neenupa@thejusengg.com
804,J D COLLEGE OF ENGINEERING & MANAGEMENT,PROF. NEETU GYANCHANDANI,gyanineetu@gmail.com
805,NMAM INSTITUTE OF TECHNOLOGY,MR.VIJAYA MURARI T.,vijayamurari.t@nitte.edu.in
806,ST. JOSEPHS COLLEGE OF ARTS AND SCIENCE (AUTONOMOUS),MR. I. BENJAMIN FRANKLIN,spoc.sjccuddalore@gmail.com
807,MAHILA   MAHAVIDYALAYA,DR.N.TIKKHA,mahila.mahavidyalayanagpur9@gmail.com
808,VELAMMAL INSTITUTE OF TECHNOLOGY,MR. S. ILAIYARAJA,hod.ece@velammalitech.edu.in
809,THE NATIONAL INSTITUE OF ENGINEERING,HARISH Y S,library@nie.ac.in
810,HKES SREE VEERENDRA PATIL DEGREE COLLEGE OF SCIENCE, ARTS & COMMERCE,NAGESH SALIMATH,hkessvp.nptel@gmail.com
811,S.L.N. COLLEGE OF ENGINEERING ,DR GURUNATH K B,slncespco@gmail.com
812,RAJA COLLEGE OF ENGINEERING AND TECHNOLOGY ,MRS. T. SUGANYA,rcetnptel2016@gmail.com
813,METs INSTITUTE OF MANAGEMENT BHUJBAL KNOWLEDGE CITY,DR. PRASAD VASANT JOSHI,prasadj_iom@bkc.met.edu
814,KAKINADA INSTITUTE OF TECHNOLOGY & SCIENCE,BONDALA SRINIVAS,librariankitsdivili@gmail.com
815,GODAVARI INSTITUTE OF ENGINEERING & TECHNOLOGY,DR. M VARAPRASADA RAO,dean@giet.ac.in
816,PROF. RAM MEGHE INSTITUTE OF TECHNOLOGY & RESEARCH,PROF AMIT R PATHARE,arpathare@mitra.ac.in
817,COASTAL INSTITUTE OF TECHNOLOGY & MANAGEMENT,Dr. SRINIVAS ADAPA,a.srinivas@citm.ac.in
818,ROYAL SCHOOL OF ENGINEERING& TECHNOLOGY,DR.BOBBY GOSWAMI BARUAH,bobby.baruah@rgi.edu.in
819,MARIAN ENGINEERING COLLEGE,Mr. ARUN ALEX,spocmarian@gmail.com
820,NADIMPALLI SATYANARAYANA RAJU INSTITUTE OF TECHNOLOGY ,RAJASEKHARAM GULLA,spocnptel.nsrit@gmail.com
821,QUBA COLLEGE OF ENGINEERING & TECHNOLOGY   ,P. BABU ,qubaspocnptel@gmail.com
822,R.V.R. & J.C. COLLEGE OF ENGINEERING ,M.V.P. CHANDRA SEKHARA RAO,rvrjccenptel@gmail.com
823,HINDUSTAN COLLEGE OF ARTS & SCIENCE ,Mr. PARTHASARATHI ,spoc.hcas@gmail.com
824,SHARNBASVESHWAR COLLEGE OF SCIENCE, GULBARGA    ,SRIDHAR S. ANAKAL,sbcscgnptel@gmail.com
825,GOVERNMENT ENGINEERING COLLEGE, HAVERI,PROF.SHREEPAD DESAI,shreepaddesai@gmail.com
826,ALPHA ARTS AND SCIENCE COLLEGE,MR. C. JOHN PAUL,aascspocnptel@alphagroup.edu
827,MIT ARTS COMMERCE & SCIENCE COLLEGE,MR. RAHUL P. BARATHE,rpbarathe@mitacsc.ac.in
828,SHRI. SAI ANJAN RURAL B.B.A, B.COM &B.A DEGREE COLLEGE,KAMALAVVA BHAJANTRI,kamalalb.saianjan@gmail.com
829,SATYASAI ENGINEERING COLLEGE,PROF.MANAS RANJAN MOHANTY,manasmohanty1980@yahoo.com
830,INSTITUTE OF AGRI BUSINESS MANAGEMENT,DR.AMITHA SHARMA,amita@iabmbikaner.org
831,DR. M .C. SAXENA COLLEGE OF ENGINEERING &TECHNOLOGY,MRS. NAINCE SAXENA,naince09@gmail.com
832,DR.D.Y.PATIL SHCOOL OF ENGINEERING & TECHNOLOGY ,Mr. Vivek Doke,vivek.doke@dypic.in
833,MAHARASHTRA INSTITUTE OF TECHNOLOGY, AURANGABAD,MR. NIHIT AGRAWAL,Nihit.agrawal@mit.asia
834,N. B. NAVALE SINHGAD COLLEGE OF ENGINEERING,MR. ABHIJIT VIJAYKUMAR MOPHARE,avmophare.nbnscoe@gmail.com
835,Sikkim Manipal Institute of Technology,Dr. Kalpana Sharma,headcs.smit@gmail.com
836,GOVERNMENT OF INDIA, MINISTRY OF DEFENCE, R & D ORGANISATION  ,AJAY KUMAR PANDEY,akpandey@arde.drdo.in
838,C V Raman College of Engineering,Dr. Bibudhendu Pati,patibibudhendu@gmail.com
839,Institute of Engineering & Management (Ashram Campus),Prof. Krishnendu Rarhi,krishnendu.rarhi@iemcal.com
840,Future Institute of Technology,Dr. Sudipta Kumar Ghosal,sudipta.ghosal@gmail.com
841,Techno India University, West Bengal,Mr. Saptarshi Mitra,mitra.saptarshi89@gmail.com
843,Brainware University,Krishnendu Saha,ks.cs@brainwareuniversity.ac.in
844,SPECTRUM INSTITUTE OF PHARMACEUTICAL SCIENCES & RESEARCH,DHARMENDRA KUMAR,rvnimiet@gmail.com
845,SRI VENKATESWARA ENGINEERING COLLEGE FOR WOMEN,M. VIKRAM,vikram.m@svcolleges.edu.in
846,DAYANANDA SAGAR COLLEGE OF ENGINEERING,DR.C.P.S. PRAKASH,drcpsprakash@gmail.com
847,POOJYA SANE GURUJI VIDYA PRASARAK MANDALS COLLEGE OF PHARMACY,DR. LAXMIKANT BANSILAL BORSE,laxmikant.borse@gmail.com
848,JSS ACADEMY OF TECHNICAL EDUCATION, BENGALURU,DR. DAYANANDA P,dayanandap@gmail.com
850,BIRLA VISHVAKARMA MAHAVIDYALAYA ENGINEERING COLLEGE ,RASHESH P MEHTA,rpmehta@bvmengineering.ac.in
851,ABES INSTITUTE OF TECHNOLOGY,NEHA TANEJA,neha.taneja@abesit.in
852,SRI MANAKULA VINAYAGAR ENGINEERING COLLEGE ,DR. G. SHANMUGASUNDARAM,shanmugasundaram@smvec.ac.in
853,SHARADCHANDRA PAWAR COLLEGE OF ENGINEERING ,PROF. CHINCHOLE MAHESH GOKUL,chinchole.mahesh87@gmail.com
854,R.C.PATEL INSTITUTE OF TECHNOLOGY ,MR. RAGHUVANSHI VEDIYA ,vsraghuvanshi@rcpit.ac.in
855,SHREE RAMCHANDRA COLLEGE OF ENGINEERING ,PROF. HARSHVARDHAN UPADHYAY,harshupadhyay.26@gmail.com
856,PARUL INSTITUTE OF ENGINEERING & TECHNOLOGY ,DR. ARVIND R. YADAV,arvind.yadav@paruluniversity.ac.in
863,WALCHAND INSTITUTE OF TECHNOLOGY,MR. KONDEKAR VIPUL HIRALAL,vipulkondekar@gmail.com
862,MAR BASELIOS COLLEGE OF ENGINEERING AND TECHNOLOGY,RUBY MARIA SYRIAC,rubymaria00@gmail.com
877,ST. MARYS GROUP OF INSTITUTIONS, GUNTUR,DR G S KRISHNA MURTHY,murthygajula@stmarysgroup.com
859,KKR&KSR INSTITUTE OF TECHNOLOGY AND SCIENCES ,MR. M.RAMESH,mylapalli2@gmail.com
861,CH. BRAHM PRAKASH GOVERNMENT ENGINEERING COLLEGE,DR. SRINIVASA K G,hoditgec@gmail.com
860,RAJARSHI SHAHU MAHAVIDYALAYA,DR. RENUKA R. LONDHE,renu_sanskruti29@rediffmail.com
870,THADOMAL SHAHANI ENGINEERING COLLEGE,PROF. BHUSHAN JADHAV,bhushan.jadhav@tsec.edu
864,BASAVESHWAR SCIENCE COLLEGE ,DR. RAJESHWARI S. MATHAD,rmathad@gmail.com
874,JAWAHARLAL NEHRU TECHNOLOGICAL UNIVERSITY ANANTAPUR COLLEGE OF ENGINEERING,G.MURALI,murali.cse@jntua.ac.in
875,NARASARAOPETA ENGINEERING COLLEGE, GUNTUR,DR.S.N.TIRUMALA RAO,nrtecnptel@gmail.com
876,SRI VENKATESWARA COLLEGE OF ENGINEERING AND TECHNOLOGY, SRIKAKULAM,MR.K.PRAKASH RAO,svcetnptellc@gmail.com
871,ASANSOL ENGINEERING COLLEGE,MR. SABYASACHI MUKHERJEE,aec.nptel@gmail.com
872,ABACUS INSTITUTE OF ENGINEERING AND MANAGEMENT,MR. AVISHEK GUPTA,nptelspocaiem@gmail.com
873,M.H.SABOO SIDDIK COLLGE OF ENGINEERING ,DR. RAVINDRA CHANDU PATIL ,ravi.patil212@gmail.com
878,VASIREDDY VENKATADRI INSTITUTE OF TECHNOLOGY,DR.M.Y.BHANU MURTHY,mybhanu@vvit.net
879,SWAMI VIVEKANAND MAHAVIDYALAYA,DR. KODGE BHEEMASHANKAR,kodgebg@gmail.com
880,SATARA COLLEGE OF ENGINEERING & MANAGEMENT,MR. UDAYAN B. KHARADE,udayankharadel@gmail.com
881,LATE G. N. SAPKAL COLLEGE OF ENGINEERING,PROF. S.S SHINDE,shraddhashinde@gmail.com
882,JAY SHRIRAM GROUP OF INSTITUTIONS,R.GOBINATH,civil@jayshriram.edu.in
883,KIT-KALAIGNAR KARUNANIDHI INSTITUTE OF TECHNOLOGY,DR.J.MANIRAJ,maniraj_ j@rediffmail.com
884,THIRUMALA ENGINEERING COLLEGE,DR.Y.V.NARAYANA,narayana_yv@yahoo.com
889,PIMPRI CHINCHWAD COLLEGE OF ENGINEERING & RESEARCH,MRS. RUPALI SONAWANE,rupali.sonawane@pccoer.in
886,NATIONAL INSTITUTE OF TECHNOLOGY MANIPUR,DR. CHANDI CHARAN MALAKAR,chdeepm@gmail.com
887,DURGAPUR INSTITUTE OF ADVANCED TECHNOLOGY & MANAGEMENT,SOUMENDU BIKAS TRIPATHY,nptelspoc.diatm@gmail.com
888,MIDNAPORE COLLEGE,NETAI MANDAL,netaimandal1987@gmail.com
890,ARULMIGU MEENAKSHI AMMAN COLLEGE OF ENGINEERING,MS.A.SASIKALA,chemstaffamace@gmail.com
"""


class BulkAddSPOCJob(jobs.DurableJob):
    """A job that adds SPoC in bulk."""

    def __init__(self, data_dict):
        self._namespace = ''
        self._job_name = 'job-%s-%s' % (
            self.__class__.__name__, self._namespace)
        self.data_dict = data_dict


    def run(self):
        local_chapter_ids = self.data_dict.keys()
        local_chapter_keys = [
            ndb.Key(local_chapter_model.LocalChapter, lc_code) for lc_code in
            local_chapter_ids]
        local_chapters = ndb.get_multi(local_chapter_keys)

        old_spoc_emails = list()
        for lc in local_chapters:
            if lc.spoc_emails:
                old_spoc_emails += lc.spoc_emails

        for lc in local_chapters:
            spoc_emails = self.data_dict.get(lc.code)
            lc.spoc_emails = spoc_emails

        ndb.put_multi(local_chapters)
        spoc_roles.SPOCRoleManager.remove_spoc_emails_from_role(old_spoc_emails)
        spoc_roles.SPOCRoleManager.add_spoc_emails_in_role(spoc_emails)

class BulkAddSPOCHandler(BaseHandler):
    """Adds SPOC emails in bulk. Takes CSV drive ID as GET param."""

    @classmethod
    def get_data_dict(cls):

        reader = csv.reader(StringIO.StringIO(RAW_SPOC_DATA), delimiter=',')
        data_dict = dict()
        for row in reader:
            lc_code = row[0].strip()
            email = row[3].strip()
            spoc_emails = data_dict.get(lc_code, list())
            spoc_emails.append(email)
            data_dict[lc_code] = spoc_emails
        return data_dict

    def get(self):
        if not roles.Roles.is_super_admin():
            self.error(403)
            self.response.write('Forbidden\n')
            return

        data_dict = self.get_data_dict()
        job = BulkAddSPOCJob(data_dict)
        job.submit()
        self.response.write('OK\n')


global_routes = [
    ('/modules/spoc/bulk_set_spoc', BulkAddSPOCHandler)
]
